### ISSUE TITLE
I don't see a signup link as indicated

### ISSUE THREAD

**Issue by rhettc** [adafruit/io-issues#1]
Saw this, followed link but I can't find signup instructions.

  Adafruit IO is currently in closed beta. If you would like to join the beta waiting list, head over to adafruit.com/io to sign up.

Pick me! Pick me!

**Comment by jwcooper** [comment]
io.adafruit.com is the link with the sign up.

Thanks!

Justin

**Comment by rhettc** [comment]
Cool. Found it! The page on the learning section, apparently the link got scrubbed, is the the page that links to adafruit.com/io 
A very similar page without the link

Thanks!
