### ISSUE TITLE
Gauges and graphs don't work correctly with floating point numbers

### ISSUE THREAD

**Issue by conductive-skein** [adafruit/io-issues#100]
I am using a Feather HUZZAH ESP8266 with a temperature sensor to publish temperature values to Adafruit IO via MQTT. When I publish the values as float or double, they don't seem to be treated as numbers at all. The values appear on gauges and in the log for the feed, but don't appear on graphs or cause the bar on the gauge to fill with blue the way it does when I publish values as int32_t. They are also displayed with an extra space between the integer part and the decimal point, for example "63 .12".

I noticed that the examples sketches in the "Adafruit IO Basics" folder only publish numerical values as int32_t, and never as int (much less any floating-point type). Is there a more specific floating-point type that I should convert the values to in order to get the correct behavior when I publish them, or is something else wrong?

Edit: After poking around in the code for the Adafruit MQTT library, it appears that everything is ultimately sent as a string anyway, so the specific type of the argument of the publish() method of the Adafruit_MQTT_Publish object isn't relevant. Adafruit_MQTT.cpp overloads the publish() method to accept arguments of type int32_t, uint32_t, and double, as well as char*, but it calls itoa() or dtostrf() on the numeric types before sending them. The difference in behavior between integers and floating-point numbers must have to do with how they are processed on the Adafruit IO server.

**Comment by conductive-skein** [comment]
A little bit more investigation revealed that this isn't a bug in Adafruit IO, it's [a bug in the dtostrf() implementation in the Arduino core for the ESP8266](https://github.com/esp8266/Arduino/issues/726), one that's already been reported and [fixed](https://github.com/esp8266/Arduino/commit/ed77f2d42b5336cb0228119e22430d60ef2c494e), but which apparently hasn't made it into the version of the ESP8266 board that can be downloaded from the boards manager in the Arduino IDE (version 1.6.5-947-g39819f0).

**Comment by toddtreece** [comment]
@conductive-skein thanks for following up!

<img width="759" alt="screen shot 2016-01-11 at 7 14 12 pm" src="https://cloud.githubusercontent.com/assets/360020/12250762/8ce32a92-b897-11e5-983e-dcb5759d4574.png">

I have v2.0 as the stable version from the ESP8266 board package, so you might want to try upgrading to get that fix.

**Comment by conductive-skein** [comment]
I tried using v2.0 previously, but couldn't get uploads to the board to work properly. I might give it another shot, though, now that I know about this.

**Comment by jwcooper** [comment]
Thank you for discovering the root cause of the issue.  We have had a few others report something similar and this helps out a lot!

**Comment by conductive-skein** [comment]
Just confirmed that upgrading to v2.0.0 of the ESP8266 board causes uploads to the board to fail. I get a "warning: espcomm_sync failed," followed by an "error: espcomm_open failed."

**Comment by ladyada** [comment]
make sure you're using the Generic ESP8266 board config for upload - 2.0 isnt bugfree either
https://learn.adafruit.com/adafruit-feather-huzzah-esp8266/using-arduino-ide#setup-esp8266-support

**Comment by conductive-skein** [comment]
Thanks for your input @ladyada. After changing the reset method to nodemcu in the "Tools" menu, I have it working under v2.0.0 using the Generic ESP8266 Module config, and the original problem is solved.

**Comment by andreavalle** [comment]
Actually all data is sent as strings (MQTT messages) but the right syntax to deal with floating point data with the publish method is using

`publish(double value, int precision)`
