### ISSUE TITLE
Incorrect rate limiting on REST API (only allowing 1 request per minute)

### ISSUE THREAD

**Issue by andy-g** [adafruit/io-issues#101]
I'm getting rate limited on rest api calls (it seems to only allow 1 call per min) otherwise I get a `429 Too Many Requests` `Retry later` response.

I get this on any api call, such as a GET request to one of my feeds `https://io.adafruit.com/api/v1/feeds/button`

MQTT seems to be back to normal and working fine though.

**Comment by jwcooper** [comment]
Please try again. We've made some changes to the API to increase the rate again.

**Comment by andy-g** [comment]
It's working perfectly again. Thanks for the assistance @jwcooper.
