### ISSUE TITLE
Sliders and Proxy's

### ISSUE THREAD

**Issue by The-Geared-Hacker** [adafruit/io-issues#102]
Hi, when I'm connected to Adafruit through a proxy the sliders don't update automatically. But when I turned the VPN off the Sliders seemed to work again.

**Comment by toddtreece** [comment]
@The-Geared-Hacker does your proxy support websockets?

**Comment by The-Geared-Hacker** [comment]
@toddtreece that's probably it! I'll give it a go!

**Comment by jwcooper** [comment]
Closing this as it appears to be related to the proxy and not IO specifically. Thanks!
