### ISSUE TITLE
Suggestion: While in Fullscreen

### ISSUE THREAD

**Issue by CodeJunkieio** [adafruit/io-issues#103]
I found it kind of unpleasant to the eye to open the dashboard in full screen because the modules were at the top of the screen. Maybe center them vertically?

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
