### ISSUE TITLE
Line charts with multiple series don't display a legend 

### ISSUE THREAD

**Issue by iangregory** [adafruit/io-issues#104]
When charting multiple feeds on a single line chart, there is no legend to indicate which line corresponds to which feed.

**Comment by dragosmiron** [comment]
:+1: to this

**Comment by ribico** [comment]
indeed, definitely needed !

**Comment by andreavalle** [comment]
Yes please do this. It's no use to have different line colors and have no idea on what the lines refer to...

**Comment by tamboekie** [comment]
+1 from me.
I'm logging temperatures from multiple sources and I would like to distinguish between each feed.

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
