### ISSUE TITLE
Gauges and Slider should resize smaller

### ISSUE THREAD

**Issue by BitRacer** [adafruit/io-issues#106]
The dashboard looks great so far.  I woul dlike to see the Gauges and Slider go smaller.  So for example if I needed to put 5 Gauges horizontally, or 3 vertically I could do that.  Also sliders as input should be able to resize even smaller.  I gain I'm thinking a stack of sliders on the lift, controlling various settings for my IoT device.

**Comment by ndoo** [comment]
+1. Height of widgets is also a big issue on wider aspect ratios (16:9, 16:10); this dashboard can’t show all data without scrolling.
http://io.adafruit.com/andr3wyong/energy-monitor

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
