### ISSUE TITLE
Improved repaint/refresh when editing dashboards

### ISSUE THREAD

**Issue by BitRacer** [adafruit/io-issues#107]
When adding a widget to the dashboard it does not show until after I "finish editing" leave the dashboard, and return to the dashboard.  It should show immediately as I add it.

**Comment by BitRacer** [comment]
Not sure if this matters, but I'm using Google Chrome Version 47.0.2526.111 (64-bit) on OSX 10.11.1

**Comment by jwcooper** [comment]
I've noticed this as well. Thank you for the bug report. We're fixing this one ASAP.

**Comment by jwcooper** [comment]
The fix for this has been deployed.
