### ISSUE TITLE
More control on graph widget

### ISSUE THREAD

**Issue by BitRacer** [adafruit/io-issues#108]
I would like to see some finer controls con the graphing widget.

1) fill area below, woth opacity for the fill, perhaps with a fill pattern, or no fill at all, just a simple line.
2) choose display color for each metric

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
