### ISSUE TITLE
Dreaming of more control - at expense of server power

### ISSUE THREAD

**Issue by dlarue** [adafruit/io-issues#109]
I like what you've done already but even doing a simple barometric measurement has lead me to wanting more capabilities on the server side. For instance, kPA and inches of water are common data points and because there's no capability to do a simple divide it's done on IoT device and 2 feeds are needed.  What's also of interest is being able to show on the display if the data is increasing in value or decreasing. I was thinking about using color but just being able to flip the ribbon direction would work. Unfortunately that would require something on the server to check the current and previous value or yet another feed and still something in the Triggers section to manipulate the dashboard widgets.

I figure publicly stating a dream might expose others with like dreams and the server Gods feel like there's room to enable some basic/limited processing on the server to occur.

Keep up the good work.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
