### ISSUE TITLE
Text Block

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#11]
Maybe I don't understand the text block well.  What I have done is attach a feed to a text block.  Then I can get values streaming on that box, which I like.  But then the label does not show on the block.  If a text block is only for static text then why have it linkable to a feed?  Or perhaps it's both?

**Comment by jwcooper** [comment]
It's both. I'll leave this open as it is indeed confusing how it works. We almost need a short description somewhere of how each block works.

You can just create a static text block, or attach a text block to a feed, but not both at the same time. If you hover over the text (if it's attached to a feed) you'll notice it's an html input, you can also type something into the block, and hit enter to update your feed.

**Comment by TheKitty** [comment]
That is handy behavior.  Yes, possibly block documentation could handle
user use cases and expectations.

**Comment by jwcooper** [comment]
Text blocks now have labels, and require a feed. We'll have something else to just have pure labels in the future.
