### ISSUE TITLE
Live update of feeds

### ISSUE THREAD

**Issue by maurbeck** [adafruit/io-issues#111]
Any /username/feeds feed does not update live. It just sits static and you have to reload the page yourself. 

It's a little deceiving because it says "created at" less than 5 seconds ago but that was less than 5 seconds from the last time the page was loaded.

I suggest updating the feeds live for both public and private use.

**Comment by andreavalle** [comment]
Yes, that would be useful

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
