### ISSUE TITLE
"Notify me if this feed goes [X time] without an update." not working

### ISSUE THREAD

**Issue by chrowe** [adafruit/io-issues#112]
The feature described in https://github.com/adafruit/io-issues/issues/44 clearly has a UI on the site but I have not gotten any notifications.
![screen shot 2016-01-24 at 10 18 20 pm](https://cloud.githubusercontent.com/assets/240115/12541717/6c14b168-c2e8-11e5-9d53-ddc2303b58b3.png)

I have both feeds in this group set to `30 minutes` but they have gone 3 days without new data and still no notification
https://io.adafruit.com/groups/24111

**Comment by chrowe** [comment]
I am realizing that I am also not getting notifications about triggers.

**Comment by nandakrpp** [comment]
Same here.

**Comment by chrowe** [comment]
I started getting some messages Feb. 26th
@nandakrpp are you still having this issue?

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
