### ISSUE TITLE
Public dashboards don't send data

### ISSUE THREAD

**Issue by maurbeck** [adafruit/io-issues#114]
I visited a light switch dashboard that works when I'm logged in but when I toggle it as a public viewer it doesn't do anything. The button toggles but it doesn't send any signal to my device.

**Comment by chrowe** [comment]
I wonder if this is related to an issue I am having where gauges show data for me when I am logged in but not for public users. #127

**Comment by jwcooper** [comment]
Public dashboards are read-only right now. The API V2 that we recently deployed supports a more granular permissions system for feeds and dashboards that should support this. The UI hasn't been updated to utilize api v2 but we are working on it.

**Comment by fat-tire** [comment]
Any update on this?  I'm having the same issue...

**Comment by leojdepaz** [comment]
Hi, Im having the same issue. Public dashboard are visible but not sending or receaving any data. Any ideas?

**Comment by jwcooper** [comment]
Our UI has been updated to utilize the API V2, but as of now dashboards are still read-only. We have a roadmap to enable sharing and other features to take advantage of the granular permissions, but I don't have any dates as of now.

If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
