### ISSUE TITLE
Windows 10 ESP8266 Library Issue

### ISSUE THREAD

**Issue by onehandedhacks** [adafruit/io-issues#115]
I ran into a problem when trying the Home automation in the Cloud with the ESP8266 &  Adafruit IO guide. You didn't mention where to get <ESP8266WiFi.h>! Every one I could find didn't work on Windows 10, but it did work on Linux. If other people run into this they may have to dual boot linux.

**Comment by jwcooper** [comment]
Can you include more details? I'm not seeing anything that would require windows in that guide.

Thanks!
