### ISSUE TITLE
Floating data only shows as integer in Feed graphs

### ISSUE THREAD

**Issue by andreavalle** [adafruit/io-issues#116]
Feed graphs only plot and display data as integer, although values are stored with decimals.
Dashboard graphs instead show decimals correctly. See sample:

![integer](https://cloud.githubusercontent.com/assets/10116628/12695269/1e032102-c749-11e5-9a07-f7e9df31faa3.jpg)

_Note: There are several issues that have been opened on floating data not being displayed correctly, however this looks like something that has not been posted yet. Sorry if this is a duplicate instead._

Regards
Andrea

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
