### ISSUE TITLE
Feed crosstalk when creating or editing a block

### ISSUE THREAD

**Issue by ductsoup** [adafruit/io-issues#118]
In "Your Feeds" I have 10 feeds. When I create or edit a block I'm offered a choice of 14 feeds. The other 4 are not and never were mine.

![screenshot003](https://cloud.githubusercontent.com/assets/9639383/12932816/db77cd30-cf52-11e5-9b4c-b747851a58d7.jpg)
![screenshot002](https://cloud.githubusercontent.com/assets/9639383/12932820/e10e98f0-cf52-11e5-9505-a5bf8a899779.jpg)

**Comment by jwcooper** [comment]
We've repaired this issue, and are actively monitoring it to ensure it doesn't happen anymore. Thank you for this bug report.

**Comment by ductsoup** [comment]
Looks pretty fixed from here. Thanks!
