### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#12]
If a feed is not attached to a toggle block, no text or the button is displayed (blank box).  I would think it should display, but the toggle not toggleable or maybe small text at the bottom saying "No feed connected" perhaps?

I connected a feed, temperature numbers, and the toggle and title displayed.  But it was nonsensical in that a toggle should be more of a feedback to the device.

A good changable thing would be to change the button color based on an in feed.  I kind of like a numeric value - it's color is something below a certain number, different above that number - or disabled below an incoming value, enabled above.

**Comment by jwcooper** [comment]
Should be no longer possible to create a toggle without attaching a feed. Color picker is new since this issue was created and I think that would do a good job of indicating feed value status based on color, and can be configured in the client code.
