### ISSUE TITLE
Will it be open source?

### ISSUE THREAD

**Issue by zhanglongqi** [adafruit/io-issues#120]
I was always trying to do such web GUI thing, but I am not good at it.
So is it possible this project will be open source?
If not could you recommend other open source project like this so I can learn from?

Thank you so much.

**Comment by 0xFACE** [comment]
Part of the Thingspeak service is open source: https://github.com/iobridge/thingspeak

**Comment by jwcooper** [comment]
All of our client libraries are open source. We have an open source compatible server (you can use it as a proxy, or to send your own data to it on your own system, or migrate your existing data to it as well). The web UI is currently not open source.
