### ISSUE TITLE
Feeds can't be deleted while viewing the feed in /feeds/feedx

### ISSUE THREAD

**Issue by DevGorilla** [adafruit/io-issues#122]
There is a delete icon, but when I delete and return to the Feeds tab (io.adafruit.com/feeds), the feed remains. I've tested this twice with the same result.

**Comment by jwcooper** [comment]
Thanks for the bug submission.  The delete icon is for the data within the feed. Deleting the feed is currently only available from the /feeds page. Goal is to add ability to delete in both places.
