### ISSUE TITLE
Line Chart Feed Labels

### ISSUE THREAD

**Issue by tomasmcm** [adafruit/io-issues#123]
First of all, Thank you for creating this a amazing platform.

![Multiple Feeds have no labels](https://cloud.githubusercontent.com/assets/6323928/13391613/5624c8f6-decd-11e5-88e7-350f36e9fae2.png)

When you select multiple feeds to be displayed on a line chart there is no way to know which line relates to each feed. 
I would suggest adding a chart legend.

Keep up the good work :D

**Comment by chrowe** [comment]
Looks like this is a dup of #104

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
