### ISSUE TITLE
IFTTT connection drops

### ISSUE THREAD

**Issue by thenderson** [adafruit/io-issues#124]
Every few days, I receive an email like this, one per IFTTT recipe that writes to my IO feed:

---

Your Recipe ID 33839324 has been automatically turned off.

Description
Send sunrise to Glasshead feed

Created
February 19 2016 at 11:56PM

Trigger
Weather - Sunrise

Action
Adafruit - Send data to Adafruit IO
## The Recipe's fields may point to stale information or use Channels that need to be reconnected. 

To fix this, I reconnect the Adafruit channel and turn each recipe on again. However, the problem recurs every few days.

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
