### ISSUE TITLE
Unable to download location data in csv/exce/json/xml

### ISSUE THREAD

**Issue by nasulay** [adafruit/io-issues#125]
The longitude and latitude data is not present in any of the data formats. The position tag has a null value. The GPS coordinates show up in the html table but not when I try to use downloadable data formats (csv/json/xml).

**Comment by andresg747** [comment]
That is totally right. There has been no change on this one. Please consider review.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
