### ISSUE TITLE
Gauges not showing data (even though line chart is) for public users 

### ISSUE THREAD

**Issue by chrowe** [adafruit/io-issues#127]
![screen shot 2016-03-25 at 1 22 46 pm](https://cloud.githubusercontent.com/assets/240115/14049602/b0b5d3e6-f28c-11e5-9b58-f444c6e9c462.png)

https://io.adafruit.com/chrowe/garn-dashboard
https://io.adafruit.com/chrowe/root-cellar (Chart just doesn't have new data right now)

**Comment by iotmx** [comment]
I am having the same issue. 
At the dashboard I declare public the boxes.
At "Your feeds" I declare public the feeds.
Then, I log out and open the dashboard. 

The black squares will show, but neither the elements nor the data.

Gauge will sometimes work,
Toggle button wont
Momentary buttons wont

http://io.adafruit.com/grprado/myIoT

Best.
Guillermo

Left image shows the dashboard on editing mode, everything is public. Right one shows the dashboard from the site accessed when log out.
![image](https://cloud.githubusercontent.com/assets/18200750/14194674/9838b64a-f80d-11e5-8b40-95096025a222.png)

**Comment by multia** [comment]
+1 on this one : Gauges not showing in public mode, but with this detail : 
They appear when you RESIZE the browser window

![001-notshow](https://cloud.githubusercontent.com/assets/18436750/14486277/41d5602a-015c-11e6-85ef-ea5d2500d509.png)


![002-shown](https://cloud.githubusercontent.com/assets/18436750/14486282/44adb680-015c-11e6-92e2-e12ed6e6a6a2.png)

**Comment by toddtreece** [comment]
a fix was just deployed for this issue. let us know if it happens again. thanks!

**Comment by chrowe** [comment]
Works for me
