### ISSUE TITLE
Map block zoomfactor

### ISSUE THREAD

**Issue by jgmbrand** [adafruit/io-issues#129]
Why is MAP zoom set to maximum on every position update?
Suggestion : Keep zoomfactor as selected by user, do not change it on update.

**Comment by andresg747** [comment]
Hi,

I second this one. Good suggestion. Still anything on this?

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
