### ISSUE TITLE
Block update interval

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#13]
When a Toggle Block is activated in the Dashboard, the text displays "Last Updated -3 Seconds Ago" when hovering over it, it will count up through zero to positive numbers.

When it updates the last updated text each second, it looks like it displays "Last Updated 0 Seconds Ago" briefly before displaying the current "Last Updated xx Seconds Ago".

**Comment by TheKitty** [comment]
Update - this behavior is seen in other blocks also.

**Comment by TheKitty** [comment]
Now I have noticed on Toggle, the text will momentarily say "Last Updated unavailable Nan Nan Nan"

**Comment by jwcooper** [comment]
I believe this will be fixed in our next deploy. Thank you!
