### ISSUE TITLE
Failed to subscribe

### ISSUE THREAD

**Issue by ardisd** [adafruit/io-issues#130]
I have been having troubling connecting to Adafruit IO. I get  Failed to subscribe on both sample code for Ethernet and CC3000

Below is the debug information

Adafruit MQTT demo
Free RAM: 798

Init the CC3000...Added sub 0
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to wifi_workshop...Connected!
Requesting DHCP
Unable to retrieve the IP Address!

Unable to retrieve the IP Address!

IP Addr: 10.10.0.55
Netmask: 255.255.255.0
Gateway: 10.10.0.1
DHCPsrv: 10.10.0.1
DNSserv: 10.10.0.1
Connecting to MQTT... io.adafruit.com -> 52.70.203.194
Connecting to TCP
MQTT connect packet:
  [0x10], ; [0x3B],   [0x00],   [0x04], M [0x4D], Q [0x51], T [0x54], T [0x54], 
  [0x04],   [0xC2],   [0x01], , [0x2C],   [0x00],   [0x05], i [0x69], l [0x6C], 
e [0x65], d [0x64], ! [0x21],   [0x00],   [0x06], a [0x61], r [0x72], d [0x64], 
i [0x69], s [0x73], d [0x64],   [0x00],   [0x20], 7 [0x37], 1 [0x31], d [0x64], 
c [0x63], 5 [0x35], 8 [0x38], d [0x64], 7 [0x37], 1 [0x31], 8 [0x38], c [0x63], 
2 [0x32], 4 [0x34], 7 [0x37], f [0x66], a [0x61], 8 [0x38], e [0x65], 4 [0x34], 
d [0x64], 8 [0x38], f [0x66], 1 [0x31], d [0x64], 1 [0x31], 4 [0x34], 3 [0x33], 
7 [0x37], 2 [0x32], 8 [0x38], a [0x61], f [0x66], 
sendPacket returned: 61
Read packet:	  [0x20],   [0x02],   [0x00],   [0x00], 
MQTT subscription packet:
  [0x82],   [0x17],   [0x00],   [0x00],   [0x00],   [0x12], a [0x61], r [0x72], 
d [0x64], i [0x69], s [0x73], d [0x64], / [0x2F], f [0x66], e [0x65], e [0x65], 
d [0x64], s [0x73], / [0x2F], o [0x6F], n [0x6E], o [0x6F], f [0x66], f [0x66], 
  [0x00], 
sendPacket returned: 25
Read packet:	  [0x90], 
Read packet:	  [0x03], 
Malformed packet len
SubAck:	
Failed to subscribe

**Comment by toddtreece** [comment]
@ardisd we'll take a look, but you may want to reset your AIO key as soon as possible. It was included in the information you pasted into this issue.

**Comment by jwcooper** [comment]
Please post this to our forums. You'll get many more eyes on it there to help with this issue and there are other examples of similar issues to this there: https://forums.adafruit.com/viewforum.php?f=56

Thanks!
