### ISSUE TITLE
Data sent as float but not showing in feed

### ISSUE THREAD

**Issue by caldow** [adafruit/io-issues#131]
I'm using a variation of the MQTT_WINC1500 example sketch to send temperature and humidity data to my feeds from a Feather M0 WiFi (ATWINC1500) and a SHT31-D T/H breakout board.  The data seems to send OK from the sketch's point of view and dots show up in the "scrolling feed line" (not sure what it's called) near the top of the screen but no data is shown in a graph, feed or dashboard.  When I copy the float values into a uint32_t, the data shows up fine everywhere but, of course, I don't have the resolution of a float.  Is there something in the definition of the feed that I have to do for a float vs. an integer?

I'm new to this so I may be missing something obvious.

**Comment by jwcooper** [comment]
I think you might get better help on this in our forums as well: https://forums.adafruit.com/viewforum.php?f=56

I don't think this is a bug with IO at this time. In addition to the dashboard, you can view the data coming in on the individual feeds page at io.adafruit.com/feeds/feed-name
