### ISSUE TITLE
Using Name field instead of Key

### ISSUE THREAD

**Issue by maurbeck** [adafruit/io-issues#132]
`//Feed name = temp. Feed key = temp
const char TEMP_FEED[] PROGMEM = AIO_USERNAME "/feeds/temp";
Adafruit_MQTT_Publish tempgauge = Adafruit_MQTT_Publish(&mqtt, TEMP_FEED);`

I had the above set up and it was working. When I changed the name though I started to get problems.

`//Feed name = ambient temp. Feed key = temp`

After I changed the name I found another auto-generated feed. The name of that feed was temp and the key was temp-1.

I see on the [tutorial](https://learn.adafruit.com/mqtt-adafruit-io-and-you/intro-to-adafruit-mqtt) I was supposed to be using Name instead of Key though...

> Then we can create the Adafruit_MQTT_Publish object, which we also call photocell and create that with Adafruit_MQTT_Publish(&mqtt, NameOfTheFeed)

What is Key used for? I was assuming Key was used in code and Name could be anything you wanted it to be to just refer to it.

**Comment by jwcooper** [comment]
Key is an auto-generated field based on the name. We're going to be migrating to use key only for accessing feeds, and name as display only. We're just not ready yet. I'll close this issue once we deploy that feature. We'll also announce when that happens.

Right now we use a combination of id, name, and key to access feeds. Initially this was to make it as easy as possible to access your data, but it gets confusing as well.

**Comment by RTCeables** [comment]
Any update on this change, as this caught me out. 

I created a verbose name and this auto-generated a key using the io.adafruit.com UI front-end. When I insert this key into my code for purposes of publishing data to the io.adafruit broker, the system then created a new data feed under my username using the key as name field and created a new key-1. With subscribing it does work as in if I use the key field it does subscribe to the correct data feed.

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
