### ISSUE TITLE
erratic feed behavior via mqtt API

### ISSUE THREAD

**Issue by rhbroberg** [adafruit/io-issues#136]
I created a feed

https://io.adafruit.com/rhbroberg/feeds/location

and posted a lot of data to it for at least 3 weeks.  2 days ago it stopped letting me post to it, but I could post just fine to new feeds.  It had a lot of data (page showed 20000 entries).   I couldn't post to it using 'curl' from the command line as I had done previously as well.  I deleted the feed, and it disappeared from the list, but the record of the deletion wasn't in the activity for > 15 minutes.

I created the feed again, and was using it some more, and now it is refusing data again.  Yet I can still post to another feed in the same group (feed 'l').  I'm posting at 1 entry every 4s, so I don't believe I'm exceeding any limits.

Any ideas?

**Comment by toddtreece** [comment]
@rhbroberg could you give it a try again?

**Comment by rhbroberg** [comment]
Still broken.  feed ‘location’ refuses input, while feed ‘l’ works fine.  except now there’s a ‘l-1’ (el-one)

Everything was very stable for me up until a few days ago; are there changes going on in the server?

**Comment by jwcooper** [comment]
There have been changes, but they were deployed after you initially posted this issue (API V2 deployed, but not as default yet). We're not entirely sure why you aren't able to access the feed yet. Your account setup appears to be valid and without any errors. Still digging into this one.

**Comment by rhbroberg** [comment]
I have since deleted the feed and moved onto another feed ‘l’; even if I create the feed of that name again via the REST api, the mqtt interface gets jammed up posting to it.  So I’m not stuck, but maybe this helps you in figuring out the underlying woe

**Comment by mmorlan62** [comment]
Howdy from Texas. I built my first feed and dashboard yesterday morning and noted this issue starting yesterday around 4:30pm CST. (I have a Particle Core sending temperature and humidity.)

Everything was working great, yesterday, until I changed my Core's broadcast interval from ten seconds to one minute. Coming back to the project this morning, I discovered there hadn't been any data received on the Adafruit dashboard since right around that time.

This morning, I switched back to ten-second broadcast intervals and deleted and re-created the Adafruit feeds after reading this thread. I've received one data broadcast on the newly-created feeds in the last five minutes.

I can see the data going out on my Particle dashboard so I know the Core is talking to the world.

The adafruit feed ID's are 589942 & 589943. I made them public, if that helps.

Best,

Michael

**Comment by mmorlan62** [comment]
Some more info: I'm receiving erratic data from my device now. For instance, one feed misses data points that the other picks up even though my device is sending them both out at the same time.

**Comment by mmorlan62** [comment]
More info: I added a one-second delay between sending my two piece of data and the two io.adafruit feeds are working much better now.

On a side note, the Particle Core is more stable as well. Before, when feeding io.adafruit and publishing to the particle dashboard, I was experiencing "invalid case" errors.

Michael

**Comment by toddtreece** [comment]
@mmorlan62 things should be more stable at this point, and i'm guessing you might be hitting a rate limit. i'm going to close this one out for now, and i'll write a post about how to subscribe to errors and rate limit messages

**Comment by rhbroberg** [comment]
I think it may be something more than just a rate limit. The same problem happened to me, and I was nowhere near the rate limit for posting.  But my feed also showed 20k+ entries.  Is it possible we are reaching a queue limit and not a rate limit?

**Comment by toddtreece** [comment]
@rhbroberg has this happened in the last day? we just finished up some changes that should greatly improve stability. my guess is that you were just experiencing some issues that were a result of our system being under heavy load.

**Comment by rhbroberg** [comment]
No, it was a month back or so when my problems occurred.  I opened a ticket back then.  The only resolution I could do was to delete my old feed and use another feed name for a day

**Comment by toddtreece** [comment]
@rhbroberg ok. thanks for the info, and i'm guessing those issues were resolved by the recent deploys

**Comment by mmorlan62** [comment]
I'll keep my project sending, if that's of any value. I don't believe I'm exceeding any limits.  Here's the bit of relevant code that runs every ten seconds:

`            sprintf(dht_f_string, "%.1f", dht_f);
            sprintf(dht_h_string, "%.1f", dht_h);
            
            //send to io.adafruit
            aio_dht_f.send(dht_f_string);
            delay(1000);
            aio_dht_h.send(dht_h_string);
            delay(1000);
`
