### ISSUE TITLE
FONA - MQTT connection failed!

### ISSUE THREAD

**Issue by sunderj91** [adafruit/io-issues#137]
Hi,

I am trying to connect FONA 808 in geofencing project, but unable to connect mqtt. I have tried the fixes as mentioned in the comments but no use. I have tried to get the value of ret variable in the project, and its value is -1. Everything seems to be ok, since I get STATE: Connect OK.

AT+CIPSTART="TCP","io.adafruit.com","1883"
<--- OK
<--- CONNECT OK
---> AT+CIPSTATUS
<--- OK
<--- STATE: CONNECT OK
AT+CIPSEND=61
0x10 0x3B 0x0 0x4 0x4D 0x51 0x54 0x54 0x4 0xFFFFFFC2 0x1 0x2C 0x0 0x2 0x2D 0x20 0x0 0x9 0x73 0x75 0x6E 0x64 0x65 0x72 0x6A 0x39 0x31 0x0 0x20 0x38 0x30 0x61 0x62 0x65 0x63 0x66 0x30 0x66 0x63 0x35 0x64 0x34 0x62 0x61 0x37 0x61 0x35 0x32 0x65 0x65 0x64 0x39 0x64 0x36 0x32 0x32 0x37 0x30 0x31 0x35 0x66
<--- 
Connection failed
-1
Retrying MQTT connection in 5 seconds...
---> AT+CIPSTATUS
<--- 
---> AT+CIPCLOSE
<--- 
---> AT+CIPSHUT
<---

Please help me understand what could be the issue.

**Comment by jwcooper** [comment]
Closing this as I noticed you posted this in the forums already, and will get more eyes on it there.

Thanks!
