### ISSUE TITLE
Unable to Create Feed

### ISSUE THREAD

**Issue by eforumz** [adafruit/io-issues#138]
Hi all,

I am new to using Adafruit IO, and it seems like I already hit my first speed bump. I am unable to create a new feed in 4 different browsers. When I click on "CREATE FEED" the window does not close, and no feeds are created.

**Comment by aleksag** [comment]
Have the same issue, when i submit the form it returns HTTP 500:

POST https://io.adafruit.com/feeds.js 500 (Internal Server Error)

**Comment by eforumz** [comment]
yeah, I got the same internal server error as well.

**Comment by jwcooper** [comment]
Thanks for notifying us of this issue. I've deployed a fix for the 500 error. The feeds are now getting created, but they may not be loading directly into the list yet in all browsers. I'll track the separate fix for that internally.  Thanks!
