### ISSUE TITLE
Dashboard in the lamp example using digital_out.js in node for raspberryPI nor working in mobile devices, tried using chrome and safari no one works. 

### ISSUE THREAD

**Issue by manuelgop** [adafruit/io-issues#139]
Using the example of digital_out.js in raspberry with adafuit OI, works okey in chrome for desktop and mac, but in mobile devices such as android and iOS did not work

**Comment by jwcooper** [comment]
Could you post this in our forums if you're still interested? We have a lot of users and admins able to help with these options. We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
