### ISSUE TITLE
Chart mouse-hover-description needs feed name

### ISSUE THREAD

**Issue by rkam** [adafruit/io-issues#140]
When you mouse over a line, you will see a description in the upper-right. -  That description needs the feed name to be more useful on multi-feed charts.

NOTE: this is a similar request to #104, but is asking for a different change:
- #104 is asking for a new item to be added to the chart (a legend).
- This is asking for a change to an existing item - i.e. just prepend the feed name to the existing description.

Also, since feed-specific data is already retrieved to form the description, (I'm hoping that) adding the name to it should be trivial.

**Comment by jwcooper** [comment]
This should be resolved. If it is not, please post in our forums the details of your issue.

https://forums.adafruit.com/viewforum.php?f=56
