### ISSUE TITLE
Delete individual data points rather than all data

### ISSUE THREAD

**Issue by VeggieVampire** [adafruit/io-issues#141]
## Please follow the guide below:

- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use *Preview* tab above to view the rendered output of your issue

---

### Before submitting an issue make sure you have:
- [ ] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [ ] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [ ] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).

### What is the purpose of your issue?
- [ ] Bug report (encountered problems with Adafruit IO)
- [ ] Feature request (request for a new functionality)

---

### If the purpose of this *issue* is a *bug report*, please provide the full verbose output from your sketch below:

```
PASTE YOUR DEBUG OUTPUT HERE
```

---

### Description of your *issue*, a link to any related forum posts, and any other relevant info below:

*YOUR DESCRIPTION HERE*

**Comment by toddtreece** [comment]
@VeggieVampire this is possible via the API:
https://io.adafruit.com/api/docs/#!/Data/destroyData

Closing this since it should cover the request, but feel free to reopen if it doesn't.
