### ISSUE TITLE
map number ranges to uploaded images

### ISSUE THREAD

**Issue by YouMakeItIBreakIt** [adafruit/io-issues#142]
I am working on a barometer, sunny, cloudy, rainy.  How about a display like the gauge that I can split into 5 sections. Would also be useful for levels of water in a barrel.  

Or another option would be a colour change.

Thanks for all your great work on this site and all the products and all the associated learning modules.

**Comment by YouMakeItIBreakIt** [comment]
Good idea Todd

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
