### ISSUE TITLE
Text scales funny in full screen

### ISSUE THREAD

**Issue by sKr0d** [adafruit/io-issues#143]
## Please follow the guide below:
- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use _Preview_ tab above to view the rendered output of your issue

---
### Before submitting an issue make sure you have:
- [x] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [x] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [ ] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).
### What is the purpose of your issue?
- [x] Bug report (encountered problems with Adafruit IO)
- [ ] Feature request (request for a new functionality)

---
### If the purpose of this _issue_ is a _bug report_, please provide the full verbose output from your sketch below:

```
Not a code related issue, but a gui design issue instead.
```

---
### Description of your _issue_, a link to any related forum posts, and any other relevant info below:

When using Full Screen mode, the text does not scale correctly. See screenshot.
![screen shot 2016-06-24 at 9 11 22 am](https://cloud.githubusercontent.com/assets/5731246/16338708/63facb5e-39ec-11e6-887c-7a058ba66089.png)

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
