### ISSUE TITLE
Dashboard On/OFF switch is hit and miss

### ISSUE THREAD

**Issue by Robert-Vaughan** [adafruit/io-issues#145]
I have an led hooked to ESP8266 Feather Huzzah Board pin 12, but turning the led on and off from the dashboard is hit and miss.

My code is below:

/***************************************************
  Adafruit ESP8266 Sensor Module

  Must use ESP8266 Arduino from:
    https://github.com/esp8266/Arduino
  Works great with Adafruit's Huzzah ESP board:
  ----> https://www.adafruit.com/product/2471
  Adafruit invests time and resources providing this open source code,
  please support Adafruit and open-source hardware by purchasing
  products from Adafruit!
  Written by Tony DiCola for Adafruit Industries.
  MIT license, all text above must be included in any redistribution
 ****************************************************/

// Libraries
# include <ESP8266WiFi.h>
# include "Adafruit_MQTT.h"
# include "Adafruit_MQTT_Client.h"
# include "DHT.h"

const int lamp_pin = 12;
// DHT 11 sensor
# define DHTPIN 5
# define DHTTYPE DHT22

// WiFi parameters
# define WLAN_SSID       "LoftS"
# define WLAN_PASS       "WLAN_PASS"

// Adafruit IO
# define AIO_SERVER      "io.adafruit.com"
# define AIO_SERVERPORT  1883
# define AIO_USERNAME    ""
# define AIO_KEY         ""

// DHT sensor
DHT dht(DHTPIN, DHTTYPE, 15);

// Functions
void connect();

// Create an ESP8266 WiFiClient class to connect to the MQTT server.
WiFiClient client;

// Store the MQTT server, client ID, username, and password in flash memory.
const char MQTT_SERVER[] PROGMEM    = AIO_SERVER;

// Set a unique MQTT client ID using the AIO key + the date and time the sketch
// was compiled (so this should be unique across multiple devices for a user,
// alternatively you can manually set this to a GUID or other random value).
const char MQTT_CLIENTID[] PROGMEM  = AIO_KEY **DATE** **TIME**;
const char MQTT_USERNAME[] PROGMEM  = AIO_USERNAME;
const char MQTT_PASSWORD[] PROGMEM  = AIO_KEY;

// Setup the MQTT client class by passing in the WiFi client and MQTT server and login details.
Adafruit_MQTT_Client mqtt(&client, MQTT_SERVER, AIO_SERVERPORT, MQTT_CLIENTID, MQTT_USERNAME, MQTT_PASSWORD);/*****************************\* Feeds ***************************************/

// Setup feeds for temperature & humidity
const char TEMPERATURE_FEED[] PROGMEM = AIO_USERNAME "/feeds/temperature";
Adafruit_MQTT_Publish temperature = Adafruit_MQTT_Publish(&mqtt, TEMPERATURE_FEED);

// Setup feeds for temperature & humidity
const char FAHRENHEIT_FEED[] PROGMEM = AIO_USERNAME "/feeds/fahrenheit";
Adafruit_MQTT_Publish fahrenheit = Adafruit_MQTT_Publish(&mqtt, FAHRENHEIT_FEED);

const char HUMIDITY_FEED[] PROGMEM = AIO_USERNAME "/feeds/humidity";
Adafruit_MQTT_Publish humidity = Adafruit_MQTT_Publish(&mqtt, HUMIDITY_FEED);

const char ONOFF_FEED[] PROGMEM = AIO_USERNAME "/feeds/onoff";
Adafruit_MQTT_Publish onoff = Adafruit_MQTT_Publish(&mqtt, ONOFF_FEED);

const char LAMP_FEED[] PROGMEM = AIO_USERNAME "/feeds/lamp";
Adafruit_MQTT_Subscribe lamp = Adafruit_MQTT_Subscribe(&mqtt, LAMP_FEED);

/**************************\* Sketch Code ************************************/

void setup() {

  pinMode(lamp_pin, OUTPUT);

  mqtt.subscribe(&lamp);

  // Init sensor
  dht.begin();

  Serial.begin(115200);
  Serial.println(F("Adafruit IO Example"));

  // Connect to WiFi access point.
  Serial.println(); Serial.println();
  delay(10);
  Serial.print(F("Connecting to "));
  Serial.println(WLAN_SSID);

  WiFi.begin(WLAN_SSID);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(F("."));
  }
  Serial.println();

  Serial.println(F("WiFi connected"));
  Serial.println(F("IP address: "));
  Serial.println(WiFi.localIP());

  // connect to adafruit io
  connect();

}

void loop() {

  // ping adafruit io a few times to make sure we remain connected
  if(! mqtt.ping(3)) {
    // reconnect to adafruit io
    if(! mqtt.connected())
      connect();
  }

```
Adafruit_MQTT_Subscribe *subscription;
```

  // Grab the current state of the sensor
  int humidity_data = (int)dht.readHumidity();
  int temperature_data = (int)dht.readTemperature();
  int fahrenheit_data = ((int)(32+1.8*dht.readTemperature()));

  // Publish data
  if (! temperature.publish(temperature_data))
    Serial.println(F("Failed to publish temperature"));
  else
    Serial.println(F("Celsius published "));
        Serial.print(temperature_data);

```
  // Publish data
```

  if (! fahrenheit.publish(fahrenheit_data))
    Serial.println(F("Failed to publish fahrenheit"));
  else
    Serial.println(F("fahrenheit published "));
      Serial.print(fahrenheit_data);

  if (! humidity.publish(humidity_data))
    Serial.println(F("Failed to publish humidity"));
  else
    Serial.println(F("Humidity published "));
          Serial.print(humidity_data);

```
Serial.println(digitalRead(12));
```

  while (subscription = mqtt.readSubscription(1000)) {

  // we only care about the lamp events
  if (subscription == &lamp) {

```
// convert mqtt ascii payload to int
char *value = (char *)lamp.lastread;
Serial.print(F("Received: "));
Serial.println(value);

// Apply message to lamp
String message = String(value);
message.trim();
if (message == "ON") {digitalWrite(lamp_pin, HIGH);}
if (message == "OFF") {digitalWrite(lamp_pin, LOW);}
```

  }
}

  // Repeat every 2 seconds
  delay(2000);

}

// connect to adafruit io via MQTT
void connect() {

  Serial.print(F("Connecting to Adafruit IO... "));

  int8_t ret;

  while ((ret = mqtt.connect()) != 0) {

```
switch (ret) {
  case 1: Serial.println(F("Wrong protocol")); break;
  case 2: Serial.println(F("ID rejected")); break;
  case 3: Serial.println(F("Server unavail")); break;
  case 4: Serial.println(F("Bad user/pass")); break;
  case 5: Serial.println(F("Not authed")); break;
  case 6: Serial.println(F("Failed to subscribe")); break;
  default: Serial.println(F("Connection failed")); break;
}

if(ret >= 0)
  mqtt.disconnect();

Serial.println(F("Retrying connection..."));
delay(2000);
```

  }

  Serial.println(F("Adafruit IO Connected!"));

}

**Comment by artkeller** [comment]
First include is missing - how could have this been compiled (it's a syntyx error)?

`#include <ESP8266WiFi.h>  // <<<<<`

**Comment by arallsopp** [comment]
I don't think its the dashboard that's at fault here. More likely, its the line `if(! mqtt.ping(3)) {` that's talking over your subscription. If you comment it out, I suspect you'll see a much better hit rate.

A quick look suggests your loop is either in a ping state, a delay state, or very briefly running code and able to respond.

**Comment by torbinsky** [comment]
@Robert-Vaughan you should reset your Adafruit IO API key as you posted it in a public forum (here) with your code.

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
