### ISSUE TITLE
Groups GRAPH IT doesn't work for WEEK, MONTH, YEAR

### ISSUE THREAD

**Issue by erniberni** [adafruit/io-issues#146]
Hello,
I have a feed where I publish temperatures every 15s.
I included this feed in a group
When I open the group (menue "Your Groups"->groupname), select GRAPH IT for the feed, a graph is shown with live data with 50min history. 
When I select DAY the graph shows data history of approximately 12h30min - I would expect 24hours.
When I select WEEK. MONTH or YEAR the graph doesn't change at all.
Selecting LIVE STREAMING brings me back to the 50min history.

This feature is really great and a fix would be really welcome
Reinhard

**Comment by nicw** [comment]
Same here, except I only see WEEK. Clicking Day/Month/Year don't change graph. Note: I have three days of data.

**Comment by erniberni** [comment]
Analysing the request with standard web developer tools of Firefox I found that the request of data is - for every timespan selected - limited to 1000 datapoints. 
For my (new) feed with data every 1 min the DAY selection only shows data of the last 16h 50min which is approximately 1000min and 1000 data points. Same for the other selections WEEK, ..
I should be easy to fix this ? Either set to no limit or set the limit dynamically.

**Comment by erniberni** [comment]
Really no answer on that ? Is anybody from development team reading this at all?

**Comment by jwcooper** [comment]
This issue should be resolved, if this issues still persists in the latest UI refresh, please post in our forums. We've made a lot of changes to IO since this issue was posted.

https://forums.adafruit.com/viewforum.php?f=56
