### ISSUE TITLE
Ability to control gauge fill color

### ISSUE THREAD

**Issue by kridan** [adafruit/io-issues#147]
## Please follow the guide below:
- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use _Preview_ tab above to view the rendered output of your issue

---
### Before submitting an issue make sure you have:
- [X] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [X] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [X] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).
### What is the purpose of your issue?
- [ ] Bug report (encountered problems with Adafruit IO)
- [X] Feature request (request for a new functionality)

---
### If the purpose of this _issue_ is a _bug report_, please provide the full verbose output from your sketch below:

```
PASTE YOUR DEBUG OUTPUT HERE
```

---
### Description of your _issue_, a link to any related forum posts, and any other relevant info below:

It would be nice to be able to control the fill color of a gauge through the item preferences.

For bonus marks, the ability to set thresholds that would control the color :)  e.g. green if <50, yellow if between 50 and 80, red if above 80

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
