### ISSUE TITLE
Dashboard blocks disappeared

### ISSUE THREAD

**Issue by zsoltmar** [adafruit/io-issues#148]
## Please follow the guide below:
- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use _Preview_ tab above to view the rendered output of your issue

---
### Before submitting an issue make sure you have:
- [x] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [x] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [x] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).
### What is the purpose of your issue?
- [x] Bug report (encountered problems with Adafruit IO)
- [ ] Feature request (request for a new functionality)

---
### If the purpose of this _issue_ is a _bug report_, please provide the full verbose output from your sketch below:

```
PASTE YOUR DEBUG OUTPUT HERE
```

---
### Description of your _issue_, a link to any related forum posts, and any other relevant info below:

This morning, I was checking out one of my dashboards. I refreshed the page and all of the blocks disappeared. There were a total of 7 blocks. Now if I try to add a new block I get the following error: Please remove an existing block in order to add a new block. There is a limit of 10 blocks per dashboard at this time.
Here's a screenshot of the empty dashboard: https://www.dropbox.com/s/e7n9189qgca5vmq/Screenshot%202016-08-29%2012.04.10.png?dl=0
Can I have the dashboard back or should I just recreate it? Seems to me like a bug.
Love the platform though!

**Comment by karlg100** [comment]
i have the same problem.  even if i create a new dashboard, after a while, all the blocks go away.  Adafruit.io is now completely useless.

**Comment by chrowe** [comment]
This just happened for me on https://io.adafruit.com/chrowe/root-cellar
I was editing blocks about an hour ago. I updated 3 existing ones and then added a 4th.
After saving I was able to see the new changes fine when returning to the dashboard several times.

Now when got to that dashboard I see no blocks.

**Comment by chrowe** [comment]
@abachman I can leave this as is for a while if that is helpful in troubleshooting but I would like to re-add the blocks later today.

**Comment by jwcooper** [comment]
This issue should be resolved with our latest UI refresh. If the issue persists, please post on our forums: https://forums.adafruit.com/viewforum.php?f=56
