### ISSUE TITLE
Last Data in Queue Returns "400 Bad Request" Instead of "404 Not Found"

### ISSUE THREAD

**Issue by torbinsky** [adafruit/io-issues#149]
**Traceback:**

```
 File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\Adafruit_IO\client.py", line 106, in receive
    return Data.from_dict(self._get(path))
  File "C:\Python27\lib\site-packages\Adafruit_IO\client.py", line 63, in _get
    self._handle_error(response)
  File "C:\Python27\lib\site-packages\Adafruit_IO\client.py", line 56, in _handle_error
    raise RequestError(response)
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 400 Bad Request
```

**Description:**
I've been playing around with the Adafruit IO python library. When testing out the Feed receive() method, I was mislead by an HTTP status code that was returned in the traceback.

As you can see in the Traceback above, I got a 400 Bad Request status in response to calling receive() which initially lead me to believe there must be a bug in the python library as it should not be sending malformed requests to your API. A 400 status code should mean that the request is malformed, not that the resource doesn't exist.

It turned out that I had a typo in my feed name and so the problem was simply the feed I was trying to read from did not exist, but this error caused me to waste time debugging the library instead.

My suggestion is to return a 404 in the event that someone attempts to access a feed that does not exist. This would more closely follow standard REST practices and not mislead developers into thinking they are making malformed API requests.

Reproduction Steps:
- Simply make a request to `https://io.adafruit.com/api/feeds/nonexistingfeedid/data/last` and you will receive a 400 response

**Comment by jwcooper** [comment]
Thank you for the feedback. We're in the process of upgrading everything to our API v2. In the meantime, you could use it directly and it should resolve your issue: https://io.adafruit.com/api/docs/?v2

Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
