### ISSUE TITLE
Graph Block Label Text

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#15]
![aio-3-15](https://cloud.githubusercontent.com/assets/1911920/6657833/a7129714-cb57-11e4-806f-964b853d69ae.png)

Text overlaps Y axis labels if lobger than a certain length.

Possible solutions would be to limit text length or probably better to scale the text font size to the length of the title.

**Comment by jwcooper** [comment]
For now fixed this by increasing the minimum width of the graph that is allowed. A graph that size isn't terribly useful once data starts flowing in.
