### ISSUE TITLE
Suggestion : Multiple Map Feeds

### ISSUE THREAD

**Issue by Gwigga** [adafruit/io-issues#151]
Due to the nature of my project, I'd like to be able to have 2GPS / 2GSM feeds on one map to allow comparison between the route the person being searched took and the route for the person searching (dogs). 
## Please follow the guide below:
- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use _Preview_ tab above to view the rendered output of your issue

---
### Before submitting an issue make sure you have:
- [ ] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [ ] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [ ] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).
### What is the purpose of your issue?
- [ ] Bug report (encountered problems with Adafruit IO)
- [x] Feature request (request for a new functionality)

---
### If the purpose of this _issue_ is a _bug report_, please provide the full verbose output from your sketch below:

```
PASTE YOUR DEBUG OUTPUT HERE
```

---
### Description of your _issue_, a link to any related forum posts, and any other relevant info below:

_YOUR DESCRIPTION HERE_

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
