### ISSUE TITLE
io.adafruit.com SSL Certificate Expiry

### ISSUE THREAD

**Issue by trananhtuan** [adafruit/io-issues#152]
Please consider using a self-signed cert for MQTTS. The current third-party io.adafruit.com cert is going to expire on July 2017.
Due to limitations, cert fingerprint needs to be hard-coded in the microcontroller (for cert verification to work) and therefore it needs update everytime io.adafruit.com cert is re-issued . This is unreasonable for IoT devices.

**Comment by avina-z** [comment]
Agree. This means that we need to re-deploy or reconfigure micro controller when the fingerprint is updated. Is there any other option?

**Comment by trananhtuan** [comment]
Other options could be:
1) Implement cert verification via CA (not easy due to resource limitations on micro controllers).
2) Keep using the current cert beyond its expiry date (bad decision from security standpoint, as if private key is ever leaked, there is no way to revoke the cert).
3) Replace the current cert with a self-signed cert with further or no expiry date (suffer similar issues as 2) but at least it's no longer bound to io.adafruit.com cert which will be replaced every few years.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. I don't have a solution for you yet, but we are looking for a longer term solution prior to July. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
