### ISSUE TITLE
Line Chart Grid and Email Option In Trigger

### ISSUE THREAD

**Issue by laeeq2410** [adafruit/io-issues#153]
## Please follow the guide below:
- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use _Preview_ tab above to view the rendered output of your issue

---
### Before submitting an issue make sure you have:
- [x] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [x] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).
### What is the purpose of your issue?
- [x] Bug report (encountered problems with Adafruit IO)
- [x] Feature request (request for a new functionality)

---
### If the purpose of this _issue_ is a _bug report_, please provide the full verbose output from your sketch below:

Email Option in Trigger is not working
PASTE YOUR DEBUG OUTPUT HERE

```

---

### Description of your *issue*, a link to any related forum posts, and any other relevant info below:

*YOUR DESCRIPTION HERE*
1) When I select email me option in trigger setting then click save trigger so it change in to set temperature option.

2) Can we use Grid option in Line chart? 
```

**Comment by jwcooper** [comment]
Could you post this in our forums if you're still interested? We have a lot of users and admins able to help with these options. We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
