### ISSUE TITLE
Kindly increase the number of feeds limit of 10 per account to 30.

### ISSUE THREAD

**Issue by varunhr** [adafruit/io-issues#158]
## Please follow the guide below:

- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use *Preview* tab above to view the rendered output of your issue

---

### Before submitting an issue make sure you have:
- [ ] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [ ] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [ ] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).

### What is the purpose of your issue?
- [ ] Bug report (encountered problems with Adafruit IO)
- [x] Feature request (request for a new functionality)

---

### If the purpose of this *issue* is a *bug report*, please provide the full verbose output from your sketch below:

```
PASTE YOUR DEBUG OUTPUT HERE
```

---

### Description of your *issue*, a link to any related forum posts, and any other relevant info below:

*YOUR DESCRIPTION HERE*

**Comment by varunhr** [comment]
I am planning to make a automated greenhouse and i intend to collect sensor details like Temperature, humimidity,Electrical Conductivity, pH, Tank water and so on, I also would use many feeds to control some the parameters based on the sensor inputs. With only 10 feeds i Will not be able control all the parameters, so i am requesting you to increase the number of feeds per account.

**Comment by varunhr** [comment]
Restrictions on Feeds.
Kindly remove the restrictions on the number of feeds one can subscribe or publish.

**Comment by durante** [comment]
Hi, i am also working on a project, which i need more feeds! is it possible to remove restrictions?

**Comment by r0swell** [comment]
Also hoping to see more then 10max feeds!

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56

**Comment by techiesms** [comment]
No need for that. I found the solution of using single feed to control multiple devices.

I was facing the similar problem of limited feeds and then come with this solution
watch this tutorial video to know more about this trick
https://youtu.be/bn3swSJe_Hk

**Comment by timkoers** [comment]
Any updates? I currently am on the 10 feed limit, which is very sad. I need to control a few more parameters for my Airco project. I am afraid I am going to switch to another MQTT Broker when this continues.
