### ISSUE TITLE
Dashboards lost public access

### ISSUE THREAD

**Issue by chrowe** [adafruit/io-issues#159]
### Before submitting an issue make sure you have:
- [ ] ~~Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.~~ 
  - https://forums.adafruit.com won't load.
- [x] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [ ] ~~Submitted your issue to the [Adafruit IO support forum] (https://forums.adafruit.com/viewforum.php?f=56).~~ 
  - https://forums.adafruit.com won't load.

### What is the purpose of your issue?
- [x] Bug report (encountered problems with Adafruit IO)
- [ ] Feature request (request for a new functionality)

---

### Description of your *issue*, a link to any related forum posts, and any other relevant info below:

*YOUR DESCRIPTION HERE*
When I am not logged in the dashboard loads but there is no data in any of the blocks. This has been working fine and stopped working without any changes on my end. This is an issues on 2 existing dashboards and one newly created one.
https://io.adafruit.com/chrowe/root-cellar
https://io.adafruit.com/chrowe/garn-dashboard
https://io.adafruit.com/chrowe/garn2 (new)

In the Chrome console I get this when not logged in
```
Mixed Content: The page at 'https://io.adafruit.com/chrowe/garn-dashboard#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://io.adafruit.com/404'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by testtech13** [comment]
I have the same issue.  Seems like you have to be logged in to see anyones public dashboards.  I can see yours just fine if I am logged in.  But if i am not logged in then I can not see the data on your dashboards.

**Comment by testtech13** [comment]
Even more interesting is that the graphs start populating data over time if you leave the page open.  They don't seem to be able to get past data but new data is available as soon as it is published.

**Comment by chrowe** [comment]
I now seem to not be getting any data even if I am logged in.
<img width="1075" alt="screen shot 2016-12-27 at 10 28 23 pm" src="https://cloud.githubusercontent.com/assets/240115/21513208/ea1704b2-cc83-11e6-9ba0-fae1412cf304.png">

**Comment by chrowe** [comment]
I tried creating a new user and a new feed and new public feeds don't seem to be showing data either. 

I also got this message when trying to load the page
```
DataTables warning: table id=streams-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

**Comment by chrowe** [comment]
@jwcooper @toddtreece Is this not a priority for you to fix? I am using io in a production environment and will need to find another solution if this is not going to be fixed soon.

I don't want to complain about the service because it has a lot to offer and it is free but I also need to be able to count on it working if it is going to be more than just an experimental tool.

**Comment by toddtreece** [comment]
@chrowe we are very close to launching a new version of IO, and this bug was probably a result of some of the backend updates. we will take a look today at patching the public dashboards for the current version.

sorry about missing this one. i'll check my notification settings.

**Comment by abachman** [comment]
@chrowe @testtech13 we've fixed the error and pushed an update to https://io.adafruit.com, your publicly shared dashboards should be visible from anonymous browsing sessions (i.e., they're actually public again). 

This is what I'm seeing in Chrome: 
![screen shot 2017-01-05 at 11 14 31 am](https://cloud.githubusercontent.com/assets/13002/21687674/37a17770-d338-11e6-86e9-fba9a3161682.png)

Can you check and make sure it works alright for you?

**Comment by testtech13** [comment]
Yes seems to be working again.  Thank you. Looking forward to see what is new in the next version.
