### ISSUE TITLE
Graph only graphing integers

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#16]
See below.  The values to the left of the AIO screen are the console output of the values sent to the AIO Feed.  They are a float temperature and an integer light intensity.  The graph only appears to be taking the values 77 and 78 degrees even though fractional values are in the feed and the graph Y axis ticks are in tenths.
![aio-3-15-two](https://cloud.githubusercontent.com/assets/1911920/6657913/554def8a-cb59-11e4-8c06-b848c48972ac.png)

**Comment by jwcooper** [comment]
This should be fixed as of now. Thank you!
