### ISSUE TITLE
Color changing trigger block

### ISSUE THREAD

**Issue by durante** [adafruit/io-issues#161]
## Please follow the guide below:

- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use *Preview* tab above to view the rendered output of your issue

---

### Before submitting an issue make sure you have:
- [ ] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [ ] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [ ] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).

### What is the purpose of your issue?
- [ ] Bug report (encountered problems with Adafruit IO)
- [x] Feature request (request for a new functionality)

---

### If the purpose of this *issue* is a *bug report*, please provide the full verbose output from your sketch below:

```
PASTE YOUR DEBUG OUTPUT HERE
```

---

### Description of your *issue*, a link to any related forum posts, and any other relevant info below:

I would like the possibility for a Trigger Block to change color depending on the value given. To be able to set a value range for different color dashboard output. 

I would like this for de-bugging issues and for data visualization.

**Comment by jwcooper** [comment]
You can use the color picker block to send hex color values in order to show different colors on the dashboard.
