### ISSUE TITLE
Graph Axis text box labels overlap with numerical text boxes

### ISSUE THREAD

**Issue by tmbarley** [adafruit/io-issues#162]
## Please follow the guide below:

- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use *Preview* tab above to view the rendered output of your issue

---

### Before submitting an issue make sure you have:
- [X ] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=5
https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [X ] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [ ] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).

### What is the purpose of your issue?
- [ X] Bug report (encountered problems with Adafruit IO)

---

### If the purpose of this *issue* is a *bug report*, please provide the full verbose output from your sketch below:

```
PASTE YOUR DEBUG OUTPUT HERE
```

---

### Description of your *issue*, a link to any related forum posts, and any other relevant info below:

Graph Axis text box labels overlap with numerical text boxes.  I've seen this one almost every screenshot and my own dashboards.  Just recording the issues so it will be fixed eventually.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancements can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
