### ISSUE TITLE
One of the subscribed feed with On OFF button failed to work from yesterday morning

### ISSUE THREAD

**Issue by varunhr** [adafruit/io-issues#163]
one of subscribed feed "onoffvalve" stopped working since yesterday morning, Was using the feed to control my solenoid valve for my roof garden, and debugging further i noticed that if i turned on the switch no message was sent and if i turned it off i was getting the message. So i renamed the feed name to "onoff_valve" and it started working normally.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancements can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
