### ISSUE TITLE
Trigger does not send email

### ISSUE THREAD

**Issue by fpovoski** [adafruit/io-issues#164]
A trigger was create on the moisture_flag when feed is set to "1".  No email is being generated for trigger.

## Please follow the guide below:

- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use *Preview* tab above to view the rendered output of your issue

---

### Before submitting an issue make sure you have:
- [ ] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [ ] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [ ] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).

### What is the purpose of your issue?
- [ ] Bug report (encountered problems with Adafruit IO)
- [ ] Feature request (request for a new functionality)

---

### If the purpose of this *issue* is a *bug report*, please provide the full verbose output from your sketch below:

```
PASTE YOUR DEBUG OUTPUT HERE
```

---

### Description of your *issue*, a link to any related forum posts, and any other relevant info below:

*YOUR DESCRIPTION HERE*

**Comment by tavdog** [comment]
I have experienced this issue as well.  Created a and set the threshold to trigger right away and it never triggered.  Never received the an email notification (check spam folder).

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancements can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
