### ISSUE TITLE
My dashboard is not working . Only the publishing of data is work properly, and i cant control any feed with onoff button.When iam logout from my account all the feeds are reseted. So Please help me for solving this problem.

### ISSUE THREAD

**Issue by rithunrosh** [adafruit/io-issues#165]
## Please follow the guide below:

- Please read the following questions **carefully** and answer honestly.
- Mark your selections by placing an x inside the brackets. Example: [x]
- Use *Preview* tab above to view the rendered output of your issue

---

### Before submitting an issue make sure you have:
- [ ] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [ ] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [ ] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).

### What is the purpose of your issue?
- [ ] Bug report (encountered problems with Adafruit IO)
- [ ] Feature request (request for a new functionality)

---

### If the purpose of this *issue* is a *bug report*, please provide the full verbose output from your sketch below:

```
PASTE YOUR DEBUG OUTPUT HERE
```

---

### Description of your *issue*, a link to any related forum posts, and any other relevant info below:

*YOUR DESCRIPTION HERE*

**Comment by jwcooper** [comment]
This should be resolved. If it is not, please post in our forums the details of your issue.

https://forums.adafruit.com/viewforum.php?f=56

**Comment by rithunrosh** [comment]
Yes... It is solved. Thank you for the adafruit team.

On 1 Feb 2017 2:06 a.m., "Justin Cooper" <notifications@github.com> wrote:

Closed #165 <https://github.com/adafruit/io-issues/issues/165>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/adafruit/io-issues/issues/165#event-943746465>, or mute
the thread
