### ISSUE TITLE
IO Interfaces Improvements

### ISSUE THREAD

**Issue by ursachedanalexandru04** [adafruit/io-issues#167]
1) When the user is in io.adafruit.com interface, SHOP, BLOG, LEARN drop down menus should be disabled, or the entire button row should be moved a bit up. The drop down menu covers entire screen if accidentally the mouse cursor highlights it.
2) io.adafruit.com should open the default dash board (or a user selected one) on the right side of the screen. The user should be able to see the dash-board instruments without the need to navigate via menus (perhaps the user just wants to have a quick look to see if he has closed the window or what temperature is in the house) 
3) I did not notice a way to navigate from www.adafruit.com to io.adafruit.com. The first page should contain a button (link) to the io interface.

**Comment by jwcooper** [comment]
Thanks for your feedback. Items 1 and 2 are in our internal issue tracker and are good ideas. I'll add a new issue for number 3. I'll close this issue, and track it internally. Thank you!
