### ISSUE TITLE
Where to submit Bugs or Suggestions?

### ISSUE THREAD

**Issue by chrowe** [adafruit/io-issues#168]
It looks like you are moving to https://forums.adafruit.com/viewforum.php?f=56 but this repo is still here and is linked to from the "Bugs or Suggestions" menu item in IO.

**Comment by jwcooper** [comment]
The forums are the best place for issues. We copy any reported issues there into our internal issue tracker. It wasn't productive for us to maintain the two separate issue trackers anymore.
