### ISSUE TITLE
Create New Block did not succed

### ISSUE THREAD

**Issue by mchobby** [adafruit/io-issues#17]
From Welcom Dashboard > New Block (Line chart) > select "Temp" feed (created with Adafruit_IO python lib) > Create Block 

Does nothing, I have a "ReferenceError: event is not defined" in the Javascript console.
I got the same javascript error for all the block
However, the "Cancel" button works.

Running on Linux Mint, Mozilla Firefox 35.0.1 

![selection_334](https://cloud.githubusercontent.com/assets/2701466/6856515/e05b34b6-d400-11e4-9673-6afeb62e5e8d.jpg)

**Comment by mchobby** [comment]
Here some additional information on the error
![additional_error_information](https://cloud.githubusercontent.com/assets/2701466/6928539/00a95e4e-d7f5-11e4-9b80-8ee94e3e1b62.jpg)

**Comment by mchobby** [comment]
Additional information:
The Add Block feature worked with Chromium 41.0.22 (Ubuntu 14.04 / Linux Mint 17 (mate) ).
However, on the same machine, it still failing with Firefox 37.0 (Ubuntu 14.04 / Linux Mint 17 (mate) ).

**Comment by jwcooper** [comment]
This should be fixed now, thank you!
