### ISSUE TITLE
AMQJS0006E Bad Connack return code:6

### ISSUE THREAD

**Issue by rahulbats** [adafruit/io-issues#173]
hi ,
i am trying to connect to adafruit.io, and i keep getting this error sometimes.
AMQJS0006E Bad Connack return code:6

I call the connect again when this happens, but it keeps giving this error and refuses to connect.
I have read somewhere that adafruit has some rate limit, but i am not sure why it will refuse the client from connecting.

**Comment by abachman** [comment]
Hi, 

It looks like you're running into the authentication throttle, we use 6 as the connack return code in that case. It's not yet part of the MQTT standard.

We limit authentication attempts to 50 per 15 minutes right now to prevent our authentication service (which takes up more resources than a normal MQTT pub/sub message) from becoming overwhelmed and to make it very difficult for someone to guess their way into an account password through MQTT. 

Unfortunately, the only thing to do when your application or device has been throttled is to wait it out. A good strategy for making sure you avoid throttles is to make sure your client is using a long delay between reconnection attempts. 30 seconds between attempts is enough to keep a single device from overwhelming the authentication throttle.
