### ISSUE TITLE
Can't edit Dashboard and Block

### ISSUE THREAD

**Issue by sumbasu** [adafruit/io-issues#176]
Hi,

1) I am not able to add blocks in existing or new dashboards. When I select a block from New Dash boards wizard, nothing happens. Even if I click on the "X" the screen the "Choose Feed" screen doesn't close.

2) For an existing dashboard, if I try to edit an existing block by clicking on the "GEAR" icon, nothing happens. But it all used to work fine last week.

I cannot do anything now. Kindly please help.

My userid: **_sumbasu_**
![dashboard_frozen](https://user-images.githubusercontent.com/17834695/26976650-5e813a04-4d42-11e7-971a-2b40c8545289.JPG)

Regards
Sumanta Basu

**Comment by sumbasu** [comment]
Please find image related to the problem statement mentioned in 2nd point:
![block](https://user-images.githubusercontent.com/17834695/26976845-4d8b2a92-4d43-11e7-9045-9a94f0385c15.JPG)

**Comment by abachman** [comment]
Hi sumbasu,

Hmmm, troubling. We haven't made any changes in the last week that should have affected the dashboards. 

What browser are you using? Are you able to open a javascript developer console and see any error messages?

**Comment by abachman** [comment]
Nevermind, actually found the bug via some forum posts, I posted an update over there: https://forums.adafruit.com/viewtopic.php?f=56&t=118283&start=15#p592421.

I've deployed a fix and you should be able to edit blocks from the dashboard again.

**Comment by sumbasu** [comment]
Hello abachman,

Thanks a lot, it is fixed. The whole experience is really great. Next week, have a demo, I am completely dependent on Adafruit io platform, for the success of the demo.
Once again, thanks a ton for your help and support.

Regards
Sumanta
