### ISSUE TITLE
Bug: Feed name can not contain accents

### ISSUE THREAD

**Issue by PatBoud** [adafruit/io-issues#18]
Unable to use accented characters (example: é ) in feed names. It raises a server error when saving changes.

Thank you!

Top part of the error page:

ActionController::UnknownFormat
Extracted source (around line #78):           
    @feed = get_feed(@user)
    respond_to do |format|
      if @feed.update_attributes(feed_params)        
        format.html { redirect_to username_feed_path(@user.username, @feed.key) }
        format.json { render 'feeds/api/v1/show.json.rabl' }

**Comment by jwcooper** [comment]
Thanks for the report! This fix has been coded, and will be deployed within a few days.

Thanks!
