### ISSUE TITLE
Filtering feed data resets with new data

### ISSUE THREAD

**Issue by servetcoskun** [adafruit/io-issues#184]
- [X] Searched the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56) for similar issues.
- [X] Searched the [Adafruit IO issue list](https://github.com/adafruit/io-issues/search?type=Issues) for similar issues.
- [ ] Submitted your issue to the [Adafruit IO support forum](https://forums.adafruit.com/viewforum.php?f=56).

### What is the purpose of your issue?
- [X] Bug report (encountered problems with Adafruit IO)
- [ ] Feature request (request for a new functionality)

---
Below is a **gif** illustrating the issue.

![filter-bug-adafruit](https://user-images.githubusercontent.com/5569716/56496719-d46c9c00-64fa-11e9-815b-b769a8175ac4.gif)

---
Under feeds the filtering button is supposed to filter data to date intervals but only does so until a new value for that specific feed is being read. As soon as a new value is being read, it resets the interval to a default.

**Comment by brentru** [comment]
This issue has been resolved, closing...
