### ISSUE TITLE
Raspbian (latest) + Python : SSL error when trying to send data

### ISSUE THREAD

**Issue by PatBoud** [adafruit/io-issues#19]
SSL error when trying a simple aio.send from a python script on RaspberryPi running the latest Raspbian version.

**UPDATE:** Works using Python3 interpretor. Also works with default Python 2.7.3, but with a **warning** message I can ignore. Data is still sent to AIO. I would still like to get rid of the warning under Python 2.7.3, if anyone can help. Thanks.

**Error message:**
*/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see **https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning**.
  InsecurePlatformWarning*

I followed the link and read. I understand that the latest available Python for Raspbian (2.7.3) is a little too old. SSL is properly implemented starting with version 2.7.9. 

I tried to follow the procedure to ignore warnings (not recommended) and the other one to use "pyopenssl" instead, but the "import" lines in the python script give me errors.

Is there any known workaround to use Python on RaspberryPi with AIO?

Thank you!

PatBoud

**Comment by tdicola** [comment]
Oh interesting, thanks for raising the issue.  I don't remember seeing this warning, but I can't remember if I tried it on the pi yet with its Python 2.7.3 install.  I'll give it a shot to see if I can find a workaround to suppress the warning.

And yep you could switch to python 3 if you need--the library is made to work with both python 2 and 3.

**Comment by tdicola** [comment]
Ah yep I also repro the same warnings on the Pi.  I found a way to resolve it without disabling the warning (from this stackoverflow answer: http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package)--can you try running these commands on the Pi to install better SSL support for python?
```
sudo apt-get update
sudo apt-get install -y python-pip python-dev build-essential libffi-dev libssl-dev
sudo pip install requests[security]
```
It takes a little while to install (~5 mins on a Pi 2) but once installed I don't get the same warnings anymore.  Let me know if that works for you too.

I'll update the io client python readme to call out running those commands on the Pi.  Thanks for raising the issue!

**Comment by PatBoud** [comment]
Confirmed, it worked!
Install took 15 minutes on my first-gem Pi Model B.

However, it also had a negative impact on the time it takes to start-up the python script (added 10 seconds), and when publishing data (added 2 seconds).

No big deal, just wanted to let you know!

Thank you for your help!

**Comment by PatBoud** [comment]
Installed libraries on another Pi, running from USB key.
Even on this fresh install, after installing dependencies to fix the warning, it takes **25 seconds** to import:
```python
from Adafruit_IO import *
```
With my experience with my 2 RaspberryPi's (both first-gen Model B), the new security layer adds some overhead. Not a big deal, but users may need to be advised so they know it's normal for their script to take so much more time to load.

Thank you!
