### ISSUE TITLE
Suggestion: Line chart: Customizing Y axis limits

### ISSUE THREAD

**Issue by PatBoud** [adafruit/io-issues#21]
I think it would be great to allow users to set maximum and minimum values of the Y axis on line charts.

Common use case: Temperatures.
Thank you!

-PatBoud

**Comment by jwcooper** [comment]
I like this idea as well. Should be fairly easy to implement. The line charts need a lot more options and customizability, in general.

**Comment by jwcooper** [comment]
This has been added, and will be deployed in the near future. Thanks!
