### ISSUE TITLE
Trigger does not send email or publish to another feed

### ISSUE THREAD

**Issue by shellbit** [adafruit/io-issues#22]
I created a trigger IF FEED IS_EQUAL_TO VALUE test Then EMAIL_ME email@address.com

When I publish 'test' to the feed, i see the value under the feeds history but I do not receive an email.  I have also tried to change the THEN to another feed to re-route the value but the trigger does not seem to be firing in either condition.  Please advise.

**Comment by jwcooper** [comment]
This should be resolved now. Thank you!
