### ISSUE TITLE
Toggle Switch not acting on received MQTT messages

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#23]
The On/Off toggle switch is not acting like an MQTT message receiver.  Trying to send 0 for off, 1 for on.  The update feed timestamp is changing.  The MQTT message send to the feed containing the toggle return a success code.  But the toggle does not change state.

I can see that this block may have been mainly anticipated as a server - in which values are sent from the dashboard out.  It should also act as a receiver/client accepting state change messages.

It could be this is happening but I'm sending the wrong values but I have not seen AOI docs on how this is done.  Thanks, Mike

**Comment by toddtreece** [comment]
![toggle](https://cloud.githubusercontent.com/assets/360020/8392931/0d51a47c-1cc8-11e5-9823-6ea513cca17f.gif)

@TheKitty you have to send the on and off values you set in the toggle button config for the block to react to MQTT input. The toggle in the .gif above is being triggered by MQTT.

**Comment by jwcooper** [comment]
Also, here is a guide Todd wrote using the toggle block: https://learn.adafruit.com/adafruit-io-basics-digital-output/adafruit-io-setup
