### ISSUE TITLE
Documentation and UI feedback

### ISSUE THREAD

**Issue by matthijskooijman** [adafruit/io-issues#24]
AIO looks excellent and exactly what I'd be needing. Overall, I'm happy 
with the features and excellent documentation, but I've noted a few
things which are confusing or could be improved, I've put them down
below. Just see these as feedback from a user unhindered by any prior
knowledge, which might help you improve the service.

 - Editing the license of a feed happens in the feed details page, but 
   switching between private and public happens in the feed list, which
   seems a bit confusing to me (especially since you wonder what the 
   license is actually used for if a feed is private)?
 - The REST API docs at https://learn.adafruit.com/adafruit-io/feeds use
   a syntax like "GET /api/feeds(.:format)" to specify the request. I'm
   not exactly sure what this means, I suspect that () indicates 
   optional and :format is replaced by the format (so leading to 
   /api/feeds.json), but this is not specified (and the examples only 
   show the response and request headers, not request uris).
 - On that same page, the "Create new feed" section says "visibility - {public, ",
   it seems some text is lost there.
 - The feeds guide at https://learn.adafruit.com/adafruit-io-basics-feeds
   says: "You will have one feed for each type of data you send to the
   system. For example, if you have a project with temperature and 
   humidity sensors, you will need to create one feed for temperature
   and one for humidity.", to me, this suggests that if I have a 
   temperature sensor in my livingroom and one in my bedroom, I only 
   have to create one "Temperature" feed and I will later somehow create
   two different devices/places/categories/groups, each containing the 
   Temperature feed. On the same page, it mentions "If you have multiple
   projects with humidity and temperature values, you should consider
   namespacing your feed names for each project. For example,
   Greenhouse-Temp & House-Temp would be good choices for two separate
   projects that have temperature values, and will help avoid confusion
   in the future." which brings doubt to my earlier interpretation (on 
   the other hand, both temperature sensors will be part of the same 
   "measure-my-house" project, so I'm not so sure.
   
   Actually playing with the system suggests that each feed really only
   holds data from a single source, so each temperature sensor in the 
   system needs its own feed. Perhaps these docs could be clarified?
 - The feeds guide at
   https://learn.adafruit.com/adafruit-io-basics-feeds/editing-a-feed 
   says "By default, the key is a lowercase version of your feed name
   with spaces removed." but it seems spaces are actually replaced by 
   dashes (which I like a lot better, btw).

**Comment by matthijskooijman** [comment]
- Looking up the AIO authentication key in a dashboard seems a bit unexpected to me, I'd more expect it in the feeds  or settings sections.

**Comment by toddtreece** [comment]
@matthijskooijman how about:

> You will have one feed for each unique source of data you send to the system. For example, if you have a project with one temperature and two humidity sensors, you would need to create three feeds. One feed for the temperature sensor, and one feed for each humidity sensor.

also updated:

> By default, the key is a lowercase version of your feed name with any spaces replaced with dashes.

**Comment by jwcooper** [comment]
Thank you for all of the feedback, this is good stuff.

Also, just yesterday we added the AIO key to the settings page, will deploy that soon.

**Comment by matthijskooijman** [comment]
@toddtreece, your proposal sounds excellent.

**Comment by jwcooper** [comment]
I've updated the docs , and added a way to change a feed's visibility on the show feed page as suggested (right next to the license, deploying shortly). This should cover all of the feedback in this issue. Thank you!

**Comment by matthijskooijman** [comment]
All looking good, thanks :-D
