### ISSUE TITLE
Multiple feed chart display

### ISSUE THREAD

**Issue by matthijskooijman** [adafruit/io-issues#25]
It would be nice if multiple feeds could be displayed in a single chart, e.g. the temperatures of multiple rooms in a house.

This is probably fairly complex and thus something to add later, but I just wanted to state my interest already :-)

**Comment by jwcooper** [comment]
This is definitely on our TODO list. Thanks for the feedback!

**Comment by jwcooper** [comment]
This is now possible. You can add up to 5 feeds per chart now. We'll have more charting changes soon too.
