### ISSUE TITLE
Long Labels Truncated on Toggle Switch / Other Widgets

### ISSUE THREAD

**Issue by dmerand** [adafruit/io-issues#29]
In general, Adafruit IO is amazing! Keep up the great work!

If you make a label too long on a toggle switch, it will cut off behind the graphical element of the widget. See the attached images for an example. I was trying to make the label "IT Workbench Soldering Iron".

<img width="285" alt="screen shot 2015-08-13 at 12 56 35" src="https://cloud.githubusercontent.com/assets/1622979/9256062/54da3602-41bb-11e5-8a90-057c4eee3f21.png">
<img width="358" alt="screen shot 2015-08-13 at 12 58 35" src="https://cloud.githubusercontent.com/assets/1622979/9256063/54db290e-41bb-11e5-89c6-1930fc0615f3.png">

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
