### ISSUE TITLE
Dashboard Add Block

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#3]
Once a block is added, it does not show up immediately on the screen.  If the dashboard being built is being refreshed, then the block shows up.

**Comment by jwcooper** [comment]
Can you still reproduce this? I'm not able to. Is it a specific block this happens to?

Thanks!

**Comment by jwcooper** [comment]
I'm going to close this, as there has been a lot of changes to the dashboard since this issue was opened, and I'm unable to reproduce it. We can re-open if it appears again.
