### ISSUE TITLE
DashBoard Public?

### ISSUE THREAD

**Issue by sabas1080** [adafruit/io-issues#30]
Not public the dashboard, says "Your DashBoard is Public" but not is public

Excuse me my English

**Comment by jwcooper** [comment]
Hi, thank you for the feedback. Where does it say this on the app? Do you have a link I can try? I'm not able to reproduce this one yet.

**Comment by sabas1080** [comment]
Yes, here public DashBoard
http://imgur.com/nV2jS8j

share link in other PC 

http://imgur.com/vTy70im

Not work :(

The link my dashboard is 
https://io.adafruit.com/inventor/iocounter

Thanks

**Comment by jwcooper** [comment]
Is the "Personas" feed also public?

You can check that here: https://io.adafruit.com/feeds

**Comment by sabas1080** [comment]
Yeah work!!, feed public, thanks

**Comment by taralshah123** [comment]
Unable to create a sharable link for my dashboard. When i click share link button, the page just refreshed. Nothing happens.
