### ISSUE TITLE
Will code of AdafruitIO be released?

### ISSUE THREAD

**Issue by q2dg** [adafruit/io-issues#34]
I mean, like Thinkspeak (https://github.com/iobridge/thingspeak) or Data (https://github.com/sparkfun/phant) are, for instance (I know they aren't identical services to AdafruitIO but you know what I mean).
Thanks.

**Comment by jwcooper** [comment]
The idea is to open source an api compatible version of IO that would allow your exported data to continue to work without the hosted version of IO. 

Unfortunately, I don't have a timeline on when this will happen and to what extent the features of IO would be available in the open source version (auth, 3rd party services, etc).

**Comment by q2dg** [comment]
Ok, thanks a lot.
I'll close the issue until new news, then

**Comment by CharString** [comment]
It wouldn't just be nice to be able to run a non-hosted version. But making it free (libre) would open up the possibility for adding features ourselves. Like adding msgpack format to the REST api, to enable to cram as much data in a 4K request as possible, to save battery at the expense of latency.

**Comment by q2dg** [comment]
Well, if you don't mind, i'll reopen this issue, then. 
Close it if you consider it's due, please

**Comment by toddtreece** [comment]
@q2dg & @CharString: we will add msgpack to the REST API, and the first version of the open source server is here: https://github.com/adafruit/adafruit-io-node

the open source version currently only supports the REST API, but we should be adding MQTT support to it soon.

**Comment by CharString** [comment]
Wonderful! I must have missed it between all those awesome libraries ;-)
@q2dg I consider this issue closed, then.

**Comment by q2dg** [comment]
Ok!
