### ISSUE TITLE
white screen after adding 'blank' feed to group

### ISSUE THREAD

**Issue by 310weber** [adafruit/io-issues#35]
Steps to reproduce:
1. start a new group
2. one by one, add feeds to the group until there are none left to add
3. select "add feed to group" one more time and the feed name field will be blank
4. select "add feed" and instead of just returning to the group page or throwing and error, it shows a blank white screen

**Comment by jwcooper** [comment]
Thanks for the issue and the detailed steps to reproduce!

**Comment by jwcooper** [comment]
This issue is now resolved. Thank you!
