### ISSUE TITLE
FEATURE: Specify time range in REST API

### ISSUE THREAD

**Issue by rbender** [adafruit/io-issues#37]
It would be really useful to specify a time range when requesting data for a feed. The range could either be specified as pair of start/end timestamps or an offset from the current time (ie: last 12 hours).

**Comment by jwcooper** [comment]
Thanks for the feedback. This is definitely on our short-term TODO list. Much better filtering should be coming eventually.

**Comment by CiTroNaK** [comment]
Any news?

I am developing simple app (will be open source with easy Heroku deploy) for displaying feeds on Status Board (http://www.panic.com/statusboard/). I would like to have limit in request data. I really don't need to get all data from feed.

Thank you.

**Comment by abachman** [comment]
AH! Thank you for pulling our attention back, @CiTroNaK. 

I actually added a `start_time` and `end_time` parameter to the `/feeds/{feed_id}/data` API route a while ago and unhelpfully neglected to document it. 

Anyways, you can (optionally) send a date time string in `start_time` and/or `end_time` to filter down to just the time range of data you want to retrieve and I've added the appropriate documentation to https://io.adafruit.com/api/docs/#!/Data/all. You can play with the API there if you've got an API key handy.

**Comment by CiTroNaK** [comment]
@abachman Hi, great news.

What date format is required for `dateTime` parameter? How I can set these parameters in Ruby client (https://github.com/adafruit/io-client-ruby)?

Thank you.

**Comment by abachman** [comment]
If you're using Ruby already, you can check out [the Timeliness gem](https://github.com/adzap/timeliness) and the formats it accepts, that's what we're using to parse times. Basically any string that will resolve to a time, including Unix epoch timestamps, will be accepted as valid. 

If you're looking for an explicit format, you can use the format described in [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.8) which would look something like `2016-08-15T16:25:00-04:00` following the form `YYYY-MM-DDThh:mm:ssZ` where `Z` is a timezone in +/- hours offset from UTC.

We filter by the data's `created_at` field, which is stored as UTC time, but you can add a timezone to your query and it will be correctly parsed.

Also, thanks for the link to the project and the PR on io-client-ruby! It's awesome to find out what people are building with IO. I'll be taking a look at both today.
