### ISSUE TITLE
multiple feeds shown in chart

### ISSUE THREAD

**Issue by jwalter15** [adafruit/io-issues#38]
I have noticed a bug related to charts in my dashboards.  I can create a chart that shows data for only one of multiple feeds (e.g. temperature or humidity) if I create the chart before any data are posted to the feeds.  When I send data to the feed, the chart works perfectly, i.e. the data for only one feed are posted to the chart.  If I create a chart after any data have been posted to the feed (or edit an existing chart), it will show the data for all my feeds (e.g. temperature and humidity).

**Comment by jwcooper** [comment]
This should be fixed now, you may need to edit and save your chart again for the changes to take effect.
