### ISSUE TITLE
Block Suggestion

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#4]
Suggest making an indicator block.  Using text right now, but for a red light/green light there does not seem to be an indicator but I might have missed it.

**Comment by jwcooper** [comment]
This is a possibility, but for now you could use the new color picker block. Send the hex color of what you want as red or green, and it will update accordingly.

**Comment by jwcooper** [comment]
I think the color picker block works well for this use case. Send any color values to the block, and it will change to that color.
