### ISSUE TITLE
data range for y axis

### ISSUE THREAD

**Issue by JRDoty3** [adafruit/io-issues#40]
Is it possible to force the y axis to display a certain range?  Right now the graph is set to display 10 to 30 deg C but it is only displaying 26-28 deg C.   I am displaying temperature and would like the graph to show a range of 0deg C to say 40degC no matter what the data is.  I am measuring room temperature and outdoor temperature in Northern Vermont and would like to have a full range displayed so a 1 degree temperature range does not look like a large temperature swing.

**Comment by jwcooper** [comment]
This isn't possible yet, but I'll add it to the todo list to add as an option when setting up the chart block.

**Comment by jwcooper** [comment]
This is now enabled.

Thanks!
