### ISSUE TITLE
Slider value not changing 

### ISSUE THREAD

**Issue by jenseng20** [adafruit/io-issues#42]
The slider is stuck at zero

**Comment by jwcooper** [comment]
Can you try editing your block, and saving it again? I just pushed up a change that should fix it, but it requires a save to pull in the change.

**Comment by jenseng20** [comment]
I have tried editing the block but it still will not change.

**Comment by jwcooper** [comment]
what browser are you using? What is the name if your feed, if you don't mind posting it here?

**Comment by jwcooper** [comment]
Will re-open this once we can get more details to reproduce.

**Comment by jenseng20** [comment]
I am using chrome for my browser. The name of my feed is first feed.
