### ISSUE TITLE
stream block 

### ISSUE THREAD

**Issue by fmbfla** [adafruit/io-issues#43]
Is the "stream block" not Sizable?  Data is Wrapping when Stream name and Date/time are used would be nice to stretch it out

**Comment by jwcooper** [comment]
If you click edit on the dashboard, you can resize from the lower right corner of the block.  Let me know if that doesn't work.

**Comment by fmbfla** [comment]
Works now, It didn't last night. It might be my browser, could be on my end with Throttling from comcast I posted in the IO forum about the editing while IO posting and it could be related.
However the Loading of the inital page and editing seems to be better tonight.
You can close this if you like
