### ISSUE TITLE
Feature request: reactive trigger on "no data received"

### ISSUE THREAD

**Issue by MHalter** [adafruit/io-issues#44]
Hi,

It would be useful if you could define a trigger that operates when no data for a given time be received  from the transmitter. 

Thanks

Mark

**Comment by jwcooper** [comment]
I like this idea, but maybe it isn't a trigger, but a 'feed offline' alert we can enable. You could configure the amount of time for a feed to be considered offline (15min, 30min, etc). System would detect if the feed is offline, and send an email.

Would this work for your use case?

We already mark feeds as online/offline, but have it hard-coded to 2 hours for all feeds.

**Comment by MHalter** [comment]
If 'feed offline' also means that no new data were send to the feed than it should work for me. 

I only want to track, if my hardware is up and run and sends data. I don't have the possibility to access the hardware from remote. So I want to find out indirectly via the feed, if the status of the hardware is still ok. If not I want to receive an email so I can restart it by hand.

Thanks 

Mark

**Comment by jwcooper** [comment]
Yup, that's exactly what it does. If no data is received for 2 hours (user configurable in the future), it is marked as 'offline', and we can send an alert.

**Comment by MHalter** [comment]
Perfect, sounds good for me. <joke>And it is ready to use tomorrow</joke> 

Thanks a lot

Mark

**Comment by MHalter** [comment]
Sorry editor kicks my joke-tags around the last sentence

**Comment by jwcooper** [comment]
This feature is deployed now. It's a little buried (we're planning on re-working the feed settings), but if you go to an individual feeds page, such as /username/feeds/feed-key, you'll can click the EDIT link, and toggle the time frame you'd like to get notified if a feed is no longer sending data. We have increments pre-set such as 10, 30, 60, and 24 hours for now, but will adjust them based on feedback.
