### ISSUE TITLE
y-scale has rounding errors

### ISSUE THREAD

**Issue by MHalter** [adafruit/io-issues#45]
Hi,

in a first project I display temperature data from my Arduino in a line chart. The y-range starts at 20.2 °C and the max value goes to 20.5 °c. The chart should then divide the y-axis into 20.2, 20.3, 20.4 and 20.5 °C. But the chart makes probably some rounding errors. It shows 000004, 000003 instead of 20.3 and 20.4 (I could not see the decimal point and the first digit after it)

Thanks

Mark

**Comment by MHalter** [comment]
![chart](https://cloud.githubusercontent.com/assets/9248733/10024889/8d3401a0-6159-11e5-9f54-103f2e1f2e62.png)

**Comment by deckerego** [comment]
+1 - I believe I'm seeing the same issue, except with data points less than 1.0.

The dashboard does seem to plot things correctly, but the feed graph does not.

![screen shot 2015-11-16 at 13 12 48](https://cloud.githubusercontent.com/assets/532789/11190490/c47ac4c0-8c63-11e5-962c-3b088471c459.png)

**Comment by jwcooper** [comment]
This should be resolved. We switched to a new charting library that should handle this case better.
