### ISSUE TITLE
Feature request: toggle trigger

### ISSUE THREAD

**Issue by MHalter** [adafruit/io-issues#48]
Hi,

it would be handy to have a reactive trigger that only triggers an action if a status changed. As I understand if I define a "lower than" trigger an email would be send every 10 minutes if  e.g. my temperature is lower than the given value. For me it would be sufficient if one email is send than the temperature goes under a threshold and next again until the temperature climbs over it.

Or is there a way to define it even know with the given triggers?

Thanks 

Mark

**Comment by jwcooper** [comment]
There isn't a way to do this with our current setup, but I think we can get there with a few code changes.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
