### ISSUE TITLE
 getting compiler error with CC3000 & Arduino Uno & MQTT Library, can't get connected to Adafruit IO site

### ISSUE THREAD

**Issue by mtneco48** [adafruit/io-issues#50]
Have used cc3000 before many times, and have reviewed CC3000 shield startup  again today. All of my example CC3000 programs work with the CC3000 wifi and make connections to sites functioning properly, but when I try to run the Adafruit IO Basics: Digital Outputs to get familiarized with the new system and software, I am running into a problem with a compiler error using the prescribed Adafruit IO Basic Sketches/Adafruit CC3000/digital_output.ino and the loading the 3 required libraries(CC3000, MQTT and SleepyDog) .

Arduino: 1.0.6 (Windows 7), Board: "Arduino Uno"
COMPILER ERROR CODE RECEIVED:

digital_out.cpp.o: In function `connect()':
C:\Program Files (x86)\Arduino/digital_out.ino:162: undefined reference to `CC3000connect(char const*, char const*, unsigned char)'
digital_out.cpp.o: In function `setup':
C:\Program Files (x86)\Arduino/digital_out.ino:95: undefined reference to `CC3000connect(char const*, char const*, unsigned char)'

 When I run the example, mqtt_cc3k.ino, in the MQTT Library , the cc3000 says that it makes a connection to the router, but can not get a DHCP and keeps resetting.
 
OUTPUT Dialog:

Adafruit MQTT demo
Free RAM: 865

Init the CC3000...Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

What is the correct CC3000 firmware version and driverpatch version are working with the cc3000 to make the connection to Adafruit IO?  I have reloaded my CC3000 Library and it still does not work? I went back to the older version of the Arduino IDE 1.0.6 and that doesn't help???
ANY THING ELSE I SHOULD BE TRYING??

**Comment by jwcooper** [comment]
Hi, I've moved your issue to the mqtt library repo: https://github.com/adafruit/Adafruit_MQTT_Library/issues/11
