### ISSUE TITLE
Still having compiling errors with digital_in.ino and digital_out.ino for adafruit.io

### ISSUE THREAD

**Issue by mtneco48** [adafruit/io-issues#51]
I have checked all the versions of the libraries for cc3000, and MQTT and they are both up to date. The cc3000 and UNO will go through the entire example sketches for the cc3000 library folder without incident, however when I try to load and run the digital_in.ino or digital_out.ino associated with the MQTT library , I get IDE compiler errors that will not let me process the code in the Arduino. The following ERROR codes are the output:
         
Arduino: 1.0.6 (Windows 7), Board: "Arduino Uno"

digital_in.cpp.o: In function `connect()':
C:\Program Files (x86)\Arduino/digital_in.ino:164: undefined reference to `CC3000connect(char const*, char const*, unsigned char)'

line 164:  CC3000connect(WLAN_SSID, WLAN_PASS, WLAN_SECURITY);
all of these parameters have been input and defined above like in all the other cc3000 examples I did today!!! ????

digital_in.cpp.o: In function `setup':
C:\Program Files (x86)\Arduino/digital_in.ino:99: undefined reference to `CC3000connect(char const*, char const*, unsigned char)'

line 99: while (! CC3000connect(WLAN_SSID, WLAN_PASS, WLAN_SECURITY))

The only code that I see that refers to these parameters that is different from the cc3000 Library that could be in error would be :

I would appreciate any help!
Thanks
 // CC3000connect is a helper function that sets up the CC3000 and connects to
// the WiFi network. See the cc3000helper.cpp tab above for the source!
boolean CC3000connect(const char* wlan_ssid, const char* wlan_pass, uint8_t wlan_security);

Can anyone see what the problem is here? The function cc3000helper.cpp is not attaching to this main program digital_in.ino or digital_out.ino, is it suppose to?

**Comment by toddtreece** [comment]
@mtneco48 any chance you are opening the sketch from inside a `.zip` archive without extracting it? everything is working fine for me w/ arduino 1.0.6 & 1.6.5 on windows 7.

![io-basics-win7](https://cloud.githubusercontent.com/assets/360020/10338709/8223e276-6cd5-11e5-9d12-191b2b5c8503.png)

**Comment by mtneco48** [comment]
I checked all my library routines again to make sure they were extracted fully before being copied into the library folder, then ran all CC3000 examples again (they ran OK, without problems). When I ran the MQTT Library example mqtt_cc3t.ino that compiled as before, but still will not connect to adafruit.io,keeps giving me the following on the serial output and gets pass this point:

Adafruit MQTT demo
Free RAM: 865

Init the CC3000...Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles


Then I tried digital_in.ino  & digital_out.ino again and did not get a compiling errors this time so there must have been a problem with one of the library routines not extracting properly, but still I can not connect to io.adafruit.com , My serial port output for both of  these is the same as above:

Adafruit IO Example:
Free RAM: 969

Init the CC3000...Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Adafruit IO Example:
Free RAM: 969

Init the CC3000...Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Adafruit IO Example:
Free RAM: 969

Init the CC3000...Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP


Any ideas on what I should try next to resolve this connection problem? I re-extracted the CC3000, MQTT, and SleepyDog Library routines, Any other routines or libraries that could affect the connection outcome that I should try??
Is connection timing out or can't DHCP find your site io.adafruit.com?

Appreciate any ideas, Thanks for your help !

**Comment by tdicola** [comment]
It looks like the watchdog is probably resetting the sketch as it wait for DHCP from your router to assign the CC3000 an IP address.  Something that can help rule out router issues with DHCP is assigning the CC3000 a static IP address.  That way the CC3k won't have to wait for DHCP and can get started talking to your network immediately.  Check out how to set a static IP address here: https://learn.adafruit.com/adafruit-cc3000-wifi/faq#faq-11  Once set the CC3k will remember the setting so you can try the MQTT & other sketches to see if that helps get past the wait for DHCP.

**Comment by toddtreece** [comment]
the connection issues are described in #53, so i'm going to close this one since it's related to compiling issues that have been resolved
