### ISSUE TITLE
The slider shows no value text when first loaded after creation

### ISSUE THREAD

**Issue by ockeydockey** [adafruit/io-issues#52]
After creating a slider and loading the dashboard, no value text is shown.  The very second you try to slide the slider, the value text populates and the slider moves up to make room for it.  This isn't completely breaking the style of the slider, but it is inconsistent and could break touchscreen users.

Found in Google Chrome Version 45.0.2454.101 m in Windows 10 Home 64-bit.

**Comment by jwcooper** [comment]
Thank you for the feedback. This issue is fixed, and will be deployed sometime today.
