### ISSUE TITLE
Compiling errors fixed, but digital_in.ino and digital_out.ino will still not make connection to io.adafruit.com site

### ISSUE THREAD

**Issue by mtneco48** [adafruit/io-issues#53]
I checked all my library routines again to make sure they were extracted fully before being copied into the library folder, then ran all CC3000 examples again (they ran OK, without problems). When I ran the MQTT Library example mqtt_cc3k.ino that compiled as before, but still will not connect to adafruit.io,keeps giving me the following on the serial output and gets pass this point:

Adafruit MQTT demo
Free RAM: 865

Init the CC3000...Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Firmware V. : 1.24

Deleting old connection profiles

Then I tried digital_in.ino  & digital_out.ino again and did not get any compiling errors this time so there must have been a problem with one of the library routines not extracting properly, but still I can not connect to io.adafruit.com , My serial port output for both of  these is the same as above:

Adafruit IO Example:
Free RAM: 969

Init the CC3000...Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Adafruit IO Example:
Free RAM: 969

Init the CC3000...Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP
Retrying WiFi
Adafruit IO Example:
Free RAM: 969

Init the CC3000...Firmware V. : 1.24

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP

Any ideas on what I should try next to resolve this connection problem? I re-extracted the CC3000, MQTT, and SleepyDog Library routines, Any other routines or libraries that could affect the connection outcome that I should try??
Is connection timing out or can't DHCP find your site io.adafruit.com?

Appreciate any ideas, Thanks for your help !

**Comment by toddtreece** [comment]
duplicated in #60. closing this one.
