### ISSUE TITLE
Edit button not visible in dashboard when viewport < ~1030px

### ISSUE THREAD

**Issue by docmollo** [adafruit/io-issues#55]
I just started walking through the IO tutorials and I have two browser windows open - one with the tutorial and the other with IO. When viewing a Dashboard, the Edit button is missing when the browser viewport is less than 1030px. I've attached two screenshots - the first is with a 1020px-wide viewport and the second is with it 1030px wide.

![dashboard-1021px](https://cloud.githubusercontent.com/assets/6555888/10413933/1d43b912-6f73-11e5-8f9b-3318e13c2179.png)
![dashboard-1030px](https://cloud.githubusercontent.com/assets/6555888/10413934/1d46d1ec-6f73-11e5-90f7-6fa156218a4a.png)

**Comment by jwcooper** [comment]
Thank you for submitting this.  We should have this fixed early this coming week.

**Comment by jwcooper** [comment]
This should be deployed later today. Thanks!
