### ISSUE TITLE
Gauge block hiding the number

### ISSUE THREAD

**Issue by XYZAidan** [adafruit/io-issues#56]
If the Gauge block in a Dashboard is set to thick, and the window is not full screen, the number will be partially hidden.
<img width="192" alt="screen shot 2015-10-12 at 10 03 18 am" src="https://cloud.githubusercontent.com/assets/11960202/10429884/d7830fa6-70c9-11e5-9f8d-07f14fb0fb8d.png">

**Comment by slootsky** [comment]
the same thing can occur with a long floating point number.
![adafruit_gauge](https://cloud.githubusercontent.com/assets/5387861/10493440/337fb014-727f-11e5-9700-866cadc993ba.png)

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
