### ISSUE TITLE
Edit button disappears if window is too narrow

### ISSUE THREAD

**Issue by XYZAidan** [adafruit/io-issues#57]
If the window that a dashboard is in is too narrow, the edit button will disappear.

<img width="307" alt="screen shot 2015-10-12 at 10 19 36 am" src="https://cloud.githubusercontent.com/assets/11960202/10430036/ed3293d4-70ca-11e5-9e7f-41ae2dc4be74.png">

**Comment by slootsky** [comment]
+1  
Since I normally run my windows half width, I didn't realize that there WAS an edit button for a while.

**Comment by jwcooper** [comment]
Thanks for the feedback. This should be fixed in the next deploy today. The only view where the edit button won't display is in the very smallest mobile view. Right now editing on mobile would be too tedious, and not a great experience.
