### ISSUE TITLE
feature request : Jump from Dashboard to feed

### ISSUE THREAD

**Issue by slootsky** [adafruit/io-issues#58]
It would be cool if there was a way for owners of data to be able to drill from the block on the dashboard into the feed history of the data.  

I say "for owners", because I see dashboards for users as being intended to be read only while owners might need to debug or see more details.  Obviously, users of public data can find their own way to the feeds, but it seems like providing the drill down wouldn't be appropriate there (keep users at a higher level than owners).

**Comment by jwcooper** [comment]
I think we may be able to do this, and I like the idea. I'll talk to our designer and see if we can fit this in somewhere. The trick is not making the dashboard overly complicated. As it is, there is a lot going on in the dashboard, especially in edit mode.

**Comment by andreavalle** [comment]
I support this idea.
The reason is that it seems like the default when you connect to io.adafruit.com is getting the first available dashboard. If you want to see a feed you have to go back to "My Dashboards" first, then select "Your feeds" and then finally select the desided feed...

**Comment by jwcooper** [comment]
This is now deployed. You can click on the white block name text in the block to jump to the first feed fo that block. Also, you can also click the cog icon to go into edit mode to click the feed: feed-key text to get to the feed page.

As feed pages are public as well (when a feed is set to public), the link will still work for public dashboards at this time. We're open to discussing this, but I didn't find any inherent drawbacks to linking for everyone as the data is public anyways.

Thanks for the suggestion!

**Comment by andreavalle** [comment]
Cool, thanks!
Andrea

**Comment by slootsky** [comment]
Awesome. Thank you. I'll experiment soon.

**Comment by slootsky** [comment]
works great.  Thank you
