### ISSUE TITLE
Entered static IP address, but  mqtt_cpp3k.ino still does not make connection to mqtt server/io.adafruit.com

### ISSUE THREAD

**Issue by mtneco48** [adafruit/io-issues#60]
Running mqtt_cc3k.ino, still can not make a permanent connection to io.adafruit.com mqtt server?? 
Never get to MQTT Connected on Serial output, just keeps resetting my wifi connection?? Why?

This is the Serial Monitor output I am getting:

Adafruit MQTT demo
Free RAM: 865

Init the CC3000...Firmware V. : 1.32

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP

IP Addr: 192.168.1.141
Netmask: 255.255.255.0
Gateway: 192.168.1.1
DHCPsrv: 0.0.0.0
DNSserv: 68.105.28.12
Connecting to MQTT... io.adafruit.com -> Adafruit MQTT demo
Free RAM: 865

Init the CC3000...Firmware V. : 1.32

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP

IP Addr: 192.168.1.141
Netmask: 255.255.255.0
Gateway: 192.168.1.1
DHCPsrv: 0.0.0.0
DNSserv: 68.105.28.12
Connecting to MQTT... io.adafruit.com -> Adafruit MQTT demo
Free RAM: 865

Init the CC3000...Firmware V. : 1.32

Deleting old connection profiles

Attempting to connect to Wasted48...Connected!
Requesting DHCP

IP Addr: 192.168.1.141
Netmask: 255.255.255.0
Gateway: 192.168.1.1
DHCPsrv: 0.0.0.0
DNSserv: 68.105.28.12
Connecting to MQTT... io.adafruit.com -> Adafruit MQTT demo
Free RAM: 865

Init the CC3000...Firmware V. : 1.32

**Comment by toddtreece** [comment]
@mtneco48 could you post your sketch (even if it's only slightly modified) and a picture of your hardware setup? 

also, if possible, could you try to keep these cc3000 issues contained to one github issue? it makes it easier for us to follow up if we have the info in one place.

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
