### ISSUE TITLE
Feature Request: Start Dashboard in fullscreen mode

### ISSUE THREAD

**Issue by seteq** [adafruit/io-issues#61]
I'm planning to use one of the dashboards in fullscreen mode on a touch-enabled kiosk device.

An URL-parameter to start a dashboard in fullscreen-mode would be very nice like:

https://io.adafruit.com/user/dashboard?fullscreen

**Comment by jwcooper** [comment]
I wish we could do this, but the full screen mode functionality built into javascript requires user interaction in order to enable it. This prevents malicious sites from loading a page, and immediately throwing the page into full screen mode.

If you have additional ideas to make full screen work even better, we're open to feedback.

I'll leave this open for now to gather more feedback.

**Comment by seteq** [comment]
Thank you for your quick answer!

I know about the browser's security aspects of javascript initiated fullscreen, one can handle that by executing the browser with command line parameters which put the browser into kiosk or fullscreen mode.

Anyway, an option to display the dashboard without the adafruit menus (just like in the javascript-initiated fullscreen mode) would be very nice.

However - Thank you for the excellent work!

**Comment by jwcooper** [comment]
Looking at the code closer...if you launch the browser in full screen mode, IO will detect that on page load:

    set_screen_mode();

    function set_screen_mode() {
      if ($(document).fullScreen()) {

We're just using the following plugin to help manage it: https://github.com/kayahr/jquery-fullscreen-plugin

Can you test this out when launching into kiosk or full screen mode?

**Comment by jwcooper** [comment]
Scratch that, I tested it out and it didn't work. I just deployed a way to do this by passing ?fullscreen=true to the dashboard. Let me know if it doesn't work out for you.

https://io.adafruit.com/jwcooper/lights?fullscreen=true

Thanks!

**Comment by seteq** [comment]
Thanks, that's awesome and working great!
