### ISSUE TITLE
Feature request: set value of a toggle button

### ISSUE THREAD

**Issue by MHalter** [adafruit/io-issues#62]
Hi,

I want to monitor who is at home and who not. That could be displayed nicely with a toggle button. Green would mean “at home”, red would mean “absent”. For this it is necessary that the state of a toggle button can be changed from outside for example by change the buttons feed. Also it would be necessary that I can then set the toggle button to read only in the dashboard so no one could change the state by a click. And even better would be if I could separate the displayed text from the value in the feed. So an one in the feed would be display as a green label “at home” and a zero as a red label “absent”.

Thanks

Mark

**Comment by jwcooper** [comment]
Hi! You can actually do all of this now. 

You can set the "on" text, and "off" text to whatever value you want (shorter the better so it fits in the UI) when creating the toggle button block. So 'home' will be shown when green, and 'away' when red. When you send either the case-sensitive on-text of 'home' or off-text of 'away' from any device, the dashboard will sync up with the value in the buttons feed within a few milliseconds without refreshing the dashboard.

Also, the public dashboard is read-only. It currently looks like toggling the button will do something, but it doesn't get saved. If you refresh from a public dashboard after hitting the toggle, you'll see it revert back. We have a github issue created to show the buttons as disabled in public dashboards.
