### ISSUE TITLE
Grouping feeds by device

### ISSUE THREAD

**Issue by Daemach** [adafruit/io-issues#63]
There are a ton of these single-feed services these days.  I think we really need a service that groups feeds into devices, so I can see all of the data for a particular device in one place.  All of my devices have serial numbers too, so I'm looking for a service where a new device can get online, register itself, associate itself with a user account then start sending data.

Example:  https://dl.dropboxusercontent.com/u/1578778/Pictures/AirNode%20ESP/File%20Oct%2010%2C%202%2059%2016%20PM.jpeg

Air quality monitor based on the ESP8266.  Temp/humidity (SHT21), Barometric pressure, altitude and temperature (MPL3115A2) and CO2/VOC  (IAQ-core)  I would like to be able to see the humidity across all of the devices, or possibly a group based on some criteria, or all of the data streams for an individual device.

**Comment by jwcooper** [comment]
We offer groups with IO. You can largely do this right now. You could set the group name to be the serial number of your device (or whatever you want), and send groups of data in a single request using MQTT on the ESP8266.

Example here:
https://github.com/adafruit/adafruit-io-basics/blob/master/esp8266/group_sensor/group_sensor.ino

You can do all of this without interacting with the web layer other than grabbing your api key. If the individual feeds in a group do not exist, the system will automatically create them for you for each group. If the group does not exist, the system will also create that for you automatically.

Then, in the web, you can go to /groups, and view your devices all in one place. Drill down into them, graph, map etc. The only thing that is cumbersome is comparing data streams across groups. We have some fixes in progress for that. Soon graphing will be possible on the /feeds page, so you could search 'humidity', and graph that data, etc.

**Comment by Daemach** [comment]
I'll start playing with this more.  It would be good to work on comparing data streams across groups, but this is a good start.

Do you have any thoughts on what might be the easiest path to giving one of these to a non-technical user and allowing them to see some kind of a dashboard for their device only via an app?

**Comment by Daemach** [comment]
Hi Justin -

I just looked at this example, and it looks like it's sending the
temperature value, but not the humidity value.  Am I missing something?

**Comment by toddtreece** [comment]
@Daemach i just pushed a fix for that issue. check out the latest [group_sensor.ino](https://github.com/adafruit/adafruit-io-basics/blob/master/esp8266/group_sensor/group_sensor.ino) for the fix.

**Comment by Daemach** [comment]
Thanks.  If you could have a look at this one that would be great...
https://github.com/adafruit/io-issues/issues/67

**Comment by jwcooper** [comment]
I'm going to close this as it's something we support. We're continuing to work on your other issue.

We don't have an app yet (looks good on mobile though), but you can make whatever feeds you want public, and place them on a dashboard to share with users. You don't have to be signed in to view a public dashboard.
