### ISSUE TITLE
Welcome Dashboard - items don't work in Chrome

### ISSUE THREAD

**Issue by scottcher** [adafruit/io-issues#66]
I was just added to the beta last week and when I first launched io.adafruit.com it was in Chrome.  None of the objects work on the Welcome Dashboard.  They are there but when I try to click on them, I get the object selection corner UI elements and I can't actually interact with the "Try Me!" Slider.

Works fine for me in IE 11.

This is all on Windows 7, at work.

The interesting bit is that when I log in from my Mac, not connected through the corporate network and without the corporate image installed, it works fine under Chrome. That's not really the interesting bit - the interesting bit is that when I move the slider on the Mac Chrome window, the Sider Value Logger (chart) and the Slider Value (gauge) in Chrome running on my Windows machine (they one where I can't interact with the Try Me! slider) both reflect the change in near real time.

Chrome version on my Windows 7 machine is: 45.0.2454.85
Chrome version on my Mac is: 45.0.2454.101 (64bit) so not a major difference.

I suspect that this may be due to a security policy enforced on my Windows machine and not on my Mac.  As problematic as that may be to resolve, if you can shed some light on the actual policy that's causing this issue, I can look into getting that policy changed so we can use io.adafruit under Chrome.  Since it still works under IE 11, however, this is not an urgent issue.

The only error I see in the Console log is: The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers. https://io.adafruit.com/assets/application-671290d734d6e90427746c8ad1bce71e1b2226e62bccb6ae1fe7e639f87fdaa7.js

**Comment by jwcooper** [comment]
My first guess is that your work is blocking websockets. You should be able to see those in the network tab. We use websockets to communicate the near-realtime changes on the dashboard.

If I'm understanding this right though, it works fine for you on IE11 on the corporate network, and not chrome? If that's the case, I'm not entirely sure what's happening.

Do you have a red bar right below the header? Or can you see the little blocks moving from right to left?

**Comment by jwcooper** [comment]
This should be resolved. If it is not, please post in our forums the details of your issue.

https://forums.adafruit.com/viewforum.php?f=56
