### ISSUE TITLE
WDT crash on second connect when using MQTT (based on ESP8266 Group Sensor example)

### ISSUE THREAD

**Issue by Daemach** [adafruit/io-issues#67]
I'm trying to get started with the esp8266 Group Sensors example and I'm not having much luck at the moment.

[list=]
[_]The example seems to post the value for temp, but not for humidity. Copy/pasting the dtostrf and strcat functions from the temp section worked.
[_]After hacking this into my own code, it seems to work once, at least from the serial monitor, but then it does a WDT crash on the second connect attempt. See the debug output below. I have already regenerated my key ;)
[*]It says success one time every time I run this. The second time it always crashes, reboots then does it all over again. Oddly, I only see 1 single update for my feeds in the io feed list - it happened an hour ago and most of the values seem to be 0, which is really strange given that it has been looping for quite a while.
[/list]
# 

I live...
ST7735 TFT initialized!
Connecting to CalypsoAP
.................
WiFi connected
IP address: 
192.168.1.154
Connecting to Adafruit IO... Connecting to: io.adafruit.com
Connect result: 1
MQTT connect packet:
[0x10], N [0x4E], [0x00], [0x04], M [0x4D], Q [0x51], T [0x54], T [0x54], 
[0x04], Â [0xC2], [0x01], , [0x2C], [0x00], [0x0F], 0 [0x30], 8 [0x38], 
: [0x3A], 5 [0x35], 6 [0x36], : [0x3A], 1 [0x31], 6 [0x36], d [0x64], a [0x61], 
e [0x65], m [0x6D], a [0x61], c [0x63], h [0x68], [0x00], [0x07], d [0x64], 
a [0x61], e [0x65], m [0x6D], a [0x61], c [0x63], h [0x68], [0x00], ( [0x28], 
b [0x62], 0 [0x30], 5 [0x35], 6 [0x36], 1 [0x31], f [0x66], 1 [0x31], 7 [0x37], 
5 [0x35], 6 [0x36], 9 [0x39], 8 [0x38], 8 [0x38], 1 [0x31], 2 [0x32], 7 [0x37], 
5 [0x35], 1 [0x31], d [0x64], b [0x62], a [0x61], 6 [0x36], b [0x62], 5 [0x35], 
d [0x64], 9 [0x39], d [0x64], 8 [0x38], 7 [0x37], e [0x65], b [0x62], 3 [0x33], 
0 [0x30], 4 [0x34], 2 [0x32], b [0x62], 8 [0x38], 8 [0x38], 6 [0x36], a [0x61], 

sendPacket returned: 80
Read packet:    [0x20], [0x02], [0x00], [0x00], 
Adafruit IO Connected!
I'm Idle
SHT20 here --> Humidity(%RH): 48.4 Temperature(C/F): 24.9/56.9
IAQ-Core here --> 450 16 119881 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):358.25 Temp(C):26.81 Altimeter setting InHg:0.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 48.5 Temperature(C/F): 24.9/56.9
IAQ-Core here --> 450 16 119881 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100263.75 Temp(C):26.56 Altimeter setting InHg:30.09
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 48.6 Temperature(C/F): 24.8/56.8
IAQ-Core here --> 450 16 119881 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100262.00 Temp(C):26.56 Altimeter setting InHg:30.09
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 48.8 Temperature(C/F): 24.8/56.8
IAQ-Core here --> 450 16 119881 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100266.00 Temp(C):26.56 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.0 Temperature(C/F): 24.8/56.8
IAQ-Core here --> 450 16 119881 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100266.00 Temp(C):26.56 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.0 Temperature(C/F): 24.7/56.7
IAQ-Core here --> 450 16 119881 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100262.25 Temp(C):26.50 Altimeter setting InHg:30.09
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.0 Temperature(C/F): 24.7/56.7
IAQ-Core here --> 450 16 119881 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100265.75 Temp(C):26.50 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.0 Temperature(C/F): 24.7/56.7
IAQ-Core here --> 450 16 119881 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100264.75 Temp(C):26.50 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.0 Temperature(C/F): 24.6/56.6
IAQ-Core here --> 450 16 124096 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100263.00 Temp(C):26.44 Altimeter setting InHg:30.09
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.2 Temperature(C/F): 24.6/56.6
IAQ-Core here --> 450 16 124096 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100265.25 Temp(C):26.44 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
Flushing input buffer
MQTT ping packet:
À [0xC0], [0x00], 
sendPacket returned: 2
Read packet:    Ð [0xD0], [0x00], 

Sending: 
Altitude,89.56
Temperature,24.58
Humidity,49.15
Temperature2,26.44
AirQuality,450.00
Pressure,30.10
MQTT publish packet:
0 [0x30], ‚ [0x82], [0x00], [0x1D], d [0x64], a [0x61], e [0x65], m [0x6D], 
a [0x61], c [0x63], h [0x68], / [0x2F], g [0x67], r [0x72], o [0x6F], u [0x75], 
p [0x70], s [0x73], / [0x2F], a [0x61], i [0x69], r [0x72], Q [0x51], u [0x75], 
a [0x61], l [0x6C], i [0x69], t [0x74], y [0x79], / [0x2F], c [0x63], s [0x73], 
v [0x76], A [0x41], l [0x6C], t [0x74], i [0x69], t [0x74], u [0x75], d [0x64], 
e [0x65], , [0x2C], 8 [0x38], 9 [0x39], . [0x2E], 5 [0x35], 6 [0x36], [0x0A], 
T [0x54], e [0x65], m [0x6D], p [0x70], e [0x65], r [0x72], a [0x61], t [0x74], 
u [0x75], r [0x72], e [0x65], , [0x2C], 2 [0x32], 4 [0x34], . [0x2E], 5 [0x35], 
8 [0x38], [0x0A], H [0x48], u [0x75], m [0x6D], i [0x69], d [0x64], i [0x69], 
t [0x74], y [0x79], , [0x2C], 4 [0x34], 9 [0x39], . [0x2E], 1 [0x31], 5 [0x35], 
[0x0A], T [0x54], e [0x65], m [0x6D], p [0x70], e [0x65], r [0x72], a [0x61], 
t [0x74], u [0x75], r [0x72], e [0x65], 2 [0x32], , [0x2C], 2 [0x32], 6 [0x36], 
. [0x2E], 4 [0x34], 4 [0x34], [0x0A], A [0x41], i [0x69], r [0x72], Q [0x51], 
u [0x75], a [0x61], l [0x6C], i [0x69], t [0x74], y [0x79], , [0x2C], 4 [0x34], 
5 [0x35], 0 [0x30], . [0x2E], 0 [0x30], 0 [0x30], [0x0A], P [0x50], r [0x72], 
e [0x65], s [0x73], s [0x73], u [0x75], r [0x72], e [0x65], , [0x2C], 3 [0x33], 
0 [0x30], . [0x2E], 1 [0x31], 0 [0x30], 
sendPacket returned: 132
Success!
I'm Idle
SHT20 here --> Humidity(%RH): 49.3 Temperature(C/F): 24.5/56.5
IAQ-Core here --> 450 16 124096 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100263.00 Temp(C):26.44 Altimeter setting InHg:30.09
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.3 Temperature(C/F): 24.5/56.5
IAQ-Core here --> 450 16 124096 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100267.00 Temp(C):26.44 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.4 Temperature(C/F): 24.5/56.5
IAQ-Core here --> 450 16 124096 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100265.25 Temp(C):26.44 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.4 Temperature(C/F): 24.4/56.4
IAQ-Core here --> 450 16 124096 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100266.25 Temp(C):26.37 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.5 Temperature(C/F): 24.4/56.4
IAQ-Core here --> 450 16 124096 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100267.50 Temp(C):26.37 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.5 Temperature(C/F): 24.4/56.4
IAQ-Core here --> 450 16 126813 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100268.00 Temp(C):26.37 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.6 Temperature(C/F): 24.3/56.3
IAQ-Core here --> 450 16 126813 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100266.75 Temp(C):26.37 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.7 Temperature(C/F): 24.3/56.3
IAQ-Core here --> 450 16 126813 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100264.00 Temp(C):26.31 Altimeter setting InHg:30.09
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.7 Temperature(C/F): 24.3/56.3
IAQ-Core here --> 450 16 126813 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100269.25 Temp(C):26.31 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
SHT20 here --> Humidity(%RH): 49.8 Temperature(C/F): 24.2/56.2
IAQ-Core here --> 450 16 126813 115325
MPL here --> Altitude(M/ft):89.56/293.84 Pressure(Pa):100266.75 Temp(C):26.31 Altimeter setting InHg:30.10
I'm REFRESH
I'm Idle
Flushing input buffer
MQTT ping packet:
À [0xC0], [0x00], 
Connection failed!
MQTT ping packet:
À [0xC0], [0x00], 
Connection failed!
MQTT ping packet:
À [0xC0], [0x00], 
Connection failed!
Connecting to Adafruit IO... Connecting to: io.adafruit.com
Connect result: 1
MQTT connect packet:
[0x10], N [0x4E], [0x00], [0x04], M [0x4D], Q [0x51], T [0x54], T [0x54], 
[0x04], Â [0xC2], [0x01], , [0x2C], [0x00], [0x0F], 0 [0x30], 8 [0x38], 
: [0x3A], 5 [0x35], 6 [0x36], : [0x3A], 1 [0x31], 6 [0x36], d [0x64], a [0x61], 
e [0x65], m [0x6D], a [0x61], c [0x63], h [0x68], [0x00], [0x07], d [0x64], 
a [0x61], e [0x65], m [0x6D], a [0x61], c [0x63], h [0x68], [0x00], ( [0x28], 
b [0x62], 0 [0x30], 5 [0x35], 6 [0x36], 1 [0x31], f [0x66], 1 [0x31], 7 [0x37], 
5 [0x35], 6 [0x36], 9 [0x39], 8 [0x38], 8 [0x38], 1 [0x31], 2 [0x32], 7 [0x37], 
5 [0x35], 1 [0x31], d [0x64], b [0x62], a [0x61], 6 [0x36], b [0x62], 5 [0x35], 
d [0x64], 9 [0x39], d [0x64], 8 [0x38], 7 [0x37], e [0x65], b [0x62], 3 [0x33], 
0 [0x30], 4 [0x34], 2 [0x32], b [0x62], 8 [0x38], 8 [0x38], 6 [0x36], a [0x61], 

sendPacket returned: 80
Read packet:    [0x20], [0x02], [0x00], [0x00], 

Exception (9):
epc1=0x402067a8 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00003031 depc=0x00000000

ctx: cont 
sp: 3ffebce0 end: 3ffec010 offset: 01a0

> > > stack>>>
> > > 3ffebe80: 3ffec068 0000001c 4024cfd5 3ffec03c 
> > > 3ffebe90: 3ffeab6c 3ffeab6c 3ffec068 40202728 
> > > 3ffebea0: 402019da 00000064 00000064 3ffec03c 
> > > 3ffebeb0: 3ffeab6c 3ffe8010 3ffec068 402030c9 
> > > 3ffebec0: 69746c41 65647574 2e39382c 540a3635 
> > > 3ffebed0: 65706d65 75746172 322c6572 38352e34 
> > > 3ffebee0: 6d75480a 74696469 39342c79 0a35312e 
> > > 3ffebef0: 706d6554 74617265 32657275 2e36322c 
> > > 3ffebf00: 410a3434 75517269 74696c61 35342c79 
> > > 3ffebf10: 30302e30 6572500a 72757373 30332c65 
> > > 3ffebf20: 0030312e 00000000 3fff39c8 40204d39 
> > > 3ffebf30: 3ffec068 00000001 3ffe9a29 4020d538 
> > > 3ffebf40: 00000bb8 3ffeab8e 00000004 00000000 
> > > 3ffebf50: 3ffeab6c 00000016 3ffec068 4020ac3d 
> > > 3ffebf60: 3ffe9a28 00000001 3ffec068 460ca000 
> > > 3ffebf70: 3ffec068 00000015 3ffec068 4020d60c 
> > > 3ffebf80: 3ffeab6c 3ffeab6c 3ffec068 4020d62d 
> > > 3ffebf90: 4024d018 3ffeab6c 3ffec068 40202738 
> > > 3ffebfa0: 9a01a8c0 00ffffff 0101a8c0 460ca000 
> > > 3ffebfb0: 312e3033 3f000030 3ffec068 40202936 
> > > 3ffebfc0: 3ffe9a78 9a01a8c0 00000000 00000000 
> > > 3ffebfd0: 00000000 00000000 00000016 40101ec9 
> > > 3ffebfe0: 40202129 00000000 00000000 3ffec03c 
> > > 3ffebff0: 3fffdc20 00000000 3ffec034 40202186 
> > > 3ffec000: 00000000 00000000 3ffeaff0 40100398 
> > > <<<stack<<<

ets Jan 8 2013,rst cause:2, boot mode:(1,7)

https://forums.adafruit.com/viewtopic.php?f=56&t=82996

**Comment by Daemach** [comment]
I bypassed the subscriptions section of the connect function and now it works properly.  At least from the client side...   Every connect and publish says "Success!" now, but no data is showing up in the feed list :/

**Comment by Daemach** [comment]
I regenerated my key and immediately started getting auth errors on the client side so I know that it's hitting the server.  After updating my code with the new key it is saying Success! again after every publish.

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56

**Comment by Daemach** [comment]
I didn't think IO was still alive...  I gave up on you guys months ago!
