### ISSUE TITLE
Dashboard emitting double value?

### ISSUE THREAD

**Issue by andreavalle** [adafruit/io-issues#68]
Hello,
I'm getting a strange behavior. I created a simple dashboard with a single block featuring a push button (values ON/OFF) associated to a feed.
I have two different MQTT clients subscribed to this feed.
One is Huzzah ESP8266 board running basic MQTT subscription code. The other is MQTT.fx software running from a PC.

When I push the button in the dashboard I get the message two times in both MQTT clients, although only a single value in the feed's data events (so I'm pushing the button once and there's no bouncing).
And just to double check, I have created some data on the same field from another PC using REST API, and with that I get a single value in the two clients.

Therefore, it looks like the tools in the Dashboard are publishing the value twice to MQTT subscribers.

Bug? Something wrong on my side?
Any idea anyone?

Thanks
Andrea

**Comment by ladyada** [comment]
yep its published twice - once when the message is received and other time when its saved.
