### ISSUE TITLE
Dynamic group names

### ISSUE THREAD

**Issue by Daemach** [adafruit/io-issues#69]
My new project is attempting to use AIO groups, creating both the groups and the 6 feeds that comprise them on the fly.  To do this, I need to use a dynamic group name that includes a unique serial number/ID.  The ESP.getChipID and ESP.getFlashID functions both return a unique ID that can be concatenated to increase entropy.

The problem is that the group names have to be stored in PROGMEM, and PROGMEM really,really wants to have a specific string to work with - not something concatenated on the fly.  How do I get around this issue???

From the group_sensors.ino file (my hack, anyway) - this doesn't work, of course - just demonstrating what I need to do:

[code]

// Setup the MQTT client class by passing in the WiFi client and MQTT server and login details.
Adafruit_MQTT_Client mqtt(&client, MQTT_SERVER, AIO_SERVERPORT, MQTT_CLIENTID, MQTT_USERNAME, MQTT_PASSWORD);

/****************************** Feeds ***************************************/

String serialNumber = String(ESP.getChipId()) + String(ESP.getFlashId());

// Setup a group called 'weather' for publishing changes.
// Notice MQTT group CSV paths for AIO follow the form: <username>/groups/<groupname>/csv
const char AQ_FEED[] PROGMEM = AIO_USERNAME "/groups/airQuality_" + serialNumber + "/csv";
Adafruit_MQTT_Publish airQuality = Adafruit_MQTT_Publish(&mqtt, AQ_FEED);
[/code]

**Comment by jwcooper** [comment]
I'm going to close this, as we have the issue on the MQTT library issues page now. Any of the other client libraries supports dynamic group names.

https://github.com/adafruit/Adafruit_MQTT_Library/issues/16
