### ISSUE TITLE
Wrong value returned after POST via REST API

### ISSUE THREAD

**Issue by andreavalle** [adafruit/io-issues#70]
I have noticed a weird bug that I can replicate systematically.

1) Update an existing feed via REST API (for example:
curl -H "Content-Type: application/json" -X PUT -d "{\"last_value\":\"123\"}" -H "x-aio-key: ...AIO-key..." http://io.adafruit.com/api/feeds/<feed>.json
Last_value updated correctly...

2) Dashboard block should show the new value. Instead it ignores it and keep displaying the previous value.

3) The "Your feeds" list instead is reporting the right "LAST VALUE", although it is not reporting the right value for "RECORDED" (timestamp). The value displayed there is the time the previous value was sent.

4) If I click on the field to open it, the top value in the list is not the last_value, but the previous value.

5) If I change the value of the field from the Dashboard, then the value is correctly updated over all the possible printout.

Regards
Andrea

**Comment by andreavalle** [comment]
I think I have identified the issue with more details.
You can update a feed via API in three ways:

1. By POST "value = xyz" data to a feed
2. By PUT "last_value = xyz" to a feed
3. By PATCH "last_value = xyz" to a feed

That is what I observed:
- Option 1 works correctly. The data value posted that way updates all of the following:
  - the "LAST VALUE" in Your feeds view
  - the list of values in the particular feed's view
  - any dashboard consuming the feed values.
- Options 2 and 3 are buggy. The data value posted that way only updates the "LAST VALUE" in Your feeds view. Instead the value is ignored in the list of values in the feed's view and is not visible in any dashboard consuming the feed values.

Hope it helps tracking and debugging this issue.

Andrea

**Comment by toddtreece** [comment]
@andreavalle thanks for the detailed report. we will have to update docs, and possibly switch the feed's `last_value` field to read only. it's meant to display the last value pushed to the feed data.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
