### ISSUE TITLE
Feed map issue

### ISSUE THREAD

**Issue by trixibella** [adafruit/io-issues#71]
![untitled-1](https://cloud.githubusercontent.com/assets/5875250/11014701/edcf8f4e-8507-11e5-9c22-f92a7dcad3de.jpg)

The mad doesn't load properly on first load. I have been having to edit and resize the map each time to properly see the full map.

**Comment by jwcooper** [comment]
This should be resolved. If it is not, please post in our forums the details of your issue.

https://forums.adafruit.com/viewforum.php?f=56
