### ISSUE TITLE
Dashboard doesn't seem to obey minimum y value

### ISSUE THREAD

**Issue by deckerego** [adafruit/io-issues#73]
It looks like setting the minimum y value on a dashboard line graph isn't obeyed. In this example, the lowest value is 0.832 being plotted, but it intersects the y axis. I believe from the settings the lowest value should still hover above a 0.0 value on the y axis.

![screen shot 2015-11-16 at 13 19 17](https://cloud.githubusercontent.com/assets/532789/11190650/be85d23e-8c64-11e5-8a4d-2e24244d7988.png)

![screen shot 2015-11-16 at 13 21 40](https://cloud.githubusercontent.com/assets/532789/11190698/0021ee3a-8c65-11e5-88a6-bb6c07ac2fc0.png)

**Comment by cudmore** [comment]
I am having the same problem. My graphs are not respecting values in 'Y-Axis Minimum' and 'Y-Axis Maximum'. The graphs seem to default to the min/max value in the plotted data stream?

**Comment by sakuaho** [comment]
It seemst that if Y-Axis Minimum is zero, minimum and maximum are ignored. If minimum is anything else e.g. 0.0001, both max and min values seem to work properly.

**Comment by jwcooper** [comment]
This should be resolved. We switched to a new charting library that should handle this case better.
