### ISSUE TITLE
Gauge Blocks cut off in full screen mode

### ISSUE THREAD

**Issue by kronmall** [adafruit/io-issues#76]
On Chrome the Guage blocks are not sized properly when I go to full screen mode.  Not sure if any other browsers are affected but it requires me to scroll each block to see the contents.

![image](https://cloud.githubusercontent.com/assets/15279996/11271254/de59bd20-8e92-11e5-8637-0b1ca12af619.png)

**Comment by jwcooper** [comment]
Hey, thanks for the bug report. This issue should be resolved now.
