### ISSUE TITLE
Line Chart rounds down to whole numbers

### ISSUE THREAD

**Issue by kronmall** [adafruit/io-issues#77]
I have a line chart plotting pressure and it is a straight line at 98 even though the pressure is fluctuating between 98-99, it appears to round all numbers down to 98.  Same thing happens for my temperature and humidity line charts.

![image](https://cloud.githubusercontent.com/assets/15279996/11271401/921bc56a-8e93-11e5-9cee-10bbf51952d1.png)

**Comment by jwcooper** [comment]
It looks like there is a space in your data? Looking at your numbers they appeare to be "69 .35", "49 .91", etc. Can you check if that's coming out of your sketch?

What client library are you using to send the data? MQTT? REST API?

**Comment by kronmall** [comment]
All of these numbers are "float" and I'm using the MQTT library so I'm not
sure why they would have a space.  Here's my code to publish:  tempf and
humidity are both float.

 // Publish data
  if (! temperature.publish(tempf))
    Serial.println(F("Failed to publish temperature"));
  else
    Serial.println(F("Temperature published!"));

  if (! mqtthumidity.publish(humidity))
    Serial.println(F("Failed to publish humidity"));
  else
    Serial.println(F("Humidity published!"));

  // Convert pressure from pa to kpa
//  float press2 = pressure/3386.38816;
  float press2 = pressure/1000.0;
  if (! mqttpressure.publish(press2))
    Serial.println(F("Failed to publish pressure"));
  else
    Serial.println(F("Pressure published!"));

Thanks,
Ken.

On Tue, Nov 24, 2015 at 4:24 PM, Justin Cooper <notifications@github.com>
wrote:

> It looks like there is a space in your data? Looking at your numbers they
> appeare to be "69 .35", "49 .91", etc. Can you check if that's coming out
> of your sketch?
>
> What client library are you using to send the data? MQTT? REST API?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adafruit/io-issues/issues/77#issuecomment-159409136>.
>



-- 
Ken Mulh
kenmulh@gmail.com

**Comment by kronmall** [comment]
I noticed today that if the numbers are in the hundreds there is no space to the left of the ".".  For instance 100.09 has no space but if it drops below 100 it does - "99 .98".

**Comment by slootsky** [comment]
Interesting.  I was noticing the same thing (whole numbers) with my data ( https://io.adafruit.com/sloot/feeds/temperature-1 ) but I hadn't noticed the space.  Looks like a problem with the mqtt library, not the io.adafruit display.

**Comment by slootsky** [comment]
I resolved this by writing my own sprintf -type function.  (after refers to the number of digits after the decimal place)

int mysprintf(char *dest, float f, int after)
{
  int i;
  int len;
  if ( f> 0) {
    i = f;  // hard truncate
    sprintf(dest,"%d",i);
    f -= i;
  }
  else
  {
  strcpy(dest,"0");
  }
  i = f*( 10^after);
  len = strlen(dest);
  sprintf(dest+len,".%d", i);
  return strlen(dest);
}

**Comment by toddtreece** [comment]
@slootsky sorry we haven't had time to look at this issue yet, but feel free to issue a pull request with your changes to the MQTT library if they are more reliable.

here's where the conversion happens:
https://github.com/adafruit/Adafruit_MQTT_Library/blob/master/Adafruit_MQTT.cpp#L617

**Comment by andreavalle** [comment]
I think this is due the syntax you're using to publish floating point data.
The correct syntax of the library expects a double value and an additional integer parameter to specify the decimal precision (e.g. number of decimals):

`// Convert pressure from pa to kpa
double press2 = pressure/1000.0;
if (! mqttpressure.publish(press2, 2))
  Serial.println(F("Failed to publish pressure"));
else
  Serial.println(F("Pressure published!"));`

**Comment by jwcooper** [comment]
This should be resolved. If it is not, please post in our forums the details of your issue.

https://forums.adafruit.com/viewforum.php?f=56
