### ISSUE TITLE
I cannot delete gauge

### ISSUE THREAD

**Issue by Ngsnet** [adafruit/io-issues#78]
Hello..

I have created gauge and attached feed, created two more and all was working good, then i deleted feed from feeds for the last of gauges and went back to dashboard to delete gauge too, but edit and trash icons are not clickable, i can only move or resize panel. I tried few times include going to feeds and back to dashboard.
I am using Safari 9.0.1. on El Cap OS. 

This is not real problem for me now, just reporting it for developers :-)
Denis

**Comment by Ngsnet** [comment]
To be more specific about this topic, after i have resized gauge block to max size, i could delete. I think that main problem was, that i had block title text  too long and it covered icons.

**Comment by jwcooper** [comment]
Thanks for the updated feedback. This issue has been resolved (long names over the buttons).
