### ISSUE TITLE
cannot resize text widget (intermittent)

### ISSUE THREAD

**Issue by mgk** [adafruit/io-issues#79]
Sometimes when I edit a text widget in a dashboard the diagonal resizer arrows do not appear in the lower right corner. When this happens I still have the reposition tool and can move the widget around, just not resize. Not sure what reproducible steps are yet.
- **OS**: OS X 10.11.1
- **Browser**:  46.0.2490.86 (64-bit)

<img width="306" alt="screenshot 2015-11-23 16 33 19" src="https://cloud.githubusercontent.com/assets/465265/11350701/ce725126-9200-11e5-8c61-83ec697431ac.png">

**Comment by jwcooper** [comment]
This should be resolved. If it is not, please post in our forums the details of your issue.

https://forums.adafruit.com/viewforum.php?f=56
