### ISSUE TITLE
Description Save

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#8]
Editing a dashboard to update the project description does not save even when Save is clicked.

**Comment by jwcooper** [comment]
Fixed. Thank you!

**Comment by TheKitty** [comment]
Awesome, thanks.  Hopefully "issues" I have posted have differing priority levels and I am not being picky as to aesthetics - hopefully each comment is useful in some way, whether tiny or a bit bigger.

**Comment by jwcooper** [comment]
All comments and issues are useful. Some I can fix quickly (like this one), and others will take longer due to the complexity of the issue (or if we need to re-design it, etc).
