### ISSUE TITLE
Dashboard issues on iPhone 5 Safari browser

### ISSUE THREAD

**Issue by aforaste** [adafruit/io-issues#80]
The AIO dashboard is aesthetically attractive w/ black/gray/blue and the layout intuitive.  Thanks for this service!  I've enjoyed becoming familiar with it.  A few issues I've noticed when viewing the dashboard on an iPhone 5 via Safari.  Note the iPhone is running the version of iOS prior to 9.1  (haven't updated yet):

1.)    Currently, there is a mismatch between the gauges (too small) and the text (too large).  I noticed this new format today. This is what it looks like on safari: 
![img_2456](https://cloud.githubusercontent.com/assets/11044712/11387684/06fdc2b4-92fb-11e5-9482-22840ec892e6.PNG)

Previously, a few days ago before the recent change, each of the gauges were too large for each window and truncated.  It wasn't possible to show one gauge fully without zooming in.  :

![img_2446](https://cloud.githubusercontent.com/assets/11044712/11387675/eceb7c2c-92fa-11e5-9613-8b8be8b74952.PNG)

2.)    I've observed that the AIO dashboard can be “sticky” when moving up or down as scroll to see all gauges and may get stuck  temporarily.  And the safari browser occasionally locks completely and crashes, with a message saying there was a problem and it needs to reload…then it clears after reloading.  This seems to happen particularly when the screen is rotated horizontally, then back vertically.

3.)    I was actually going to suggest a "full screen" mode as an added feature, as the dashboard is a little bit busy with all of the menus, and extra text at the top and bottom of the dashboard.  However, just noticed that is already an option today.  While it works great on my laptop (great feature), it does not work on my iphone/safari.  The hover text shows, but nothing happens when pressed.

4.) Also, when touching a point on the line chart, it identifies the X & Y axis values on a laptop, but on the iphone it says "undefined, undefined".  

Thanks.

**Comment by jwcooper** [comment]
This should be resolved. If it is not, please post in our forums the details of your issue.

https://forums.adafruit.com/viewforum.php?f=56
