### ISSUE TITLE
Adafruit.io is down

### ISSUE THREAD

**Issue by kevinmoses** [adafruit/io-issues#83]
about 3 hours ago an ifttt recipe stopped reporting to me. I checked the feed from my particle and it seems ok. I have also tried to hit the Adafruit mqtt server with MQTTLens and it will not connect. 

Recipe and Error Below. 
<img width="766" alt="screen shot 2015-12-01 at 5 38 23 am" src="https://cloud.githubusercontent.com/assets/10929989/11499728/d478a168-97ed-11e5-9f2d-6f7df1da14a0.png">
<img width="935" alt="screen shot 2015-12-01 at 5 37 33 am" src="https://cloud.githubusercontent.com/assets/10929989/11499736/e3aea02e-97ed-11e5-98b3-653d83b809d7.png">

**Comment by toddtreece** [comment]
IO should be back up. Sorry for the downtime, and thanks for the report!
