### ISSUE TITLE
[Feed graph] mouse hover giving popup "undefined"

### ISSUE THREAD

**Issue by MangaValk** [adafruit/io-issues#84]
Feed graph mouse hover giving popup "undefined at undefined" and at wrong position.
Using Chrome browser.
![adafruit bug](https://cloud.githubusercontent.com/assets/1933269/11535967/8b75707a-9916-11e5-8cc1-c62d07ded871.PNG)

**Comment by jwcooper** [comment]
This should be resolved. We switched to a new charting library that should handle this case better.
