### ISSUE TITLE
Size issues on mobile/reduced size browser

### ISSUE THREAD

**Issue by will-anderson** [adafruit/io-issues#85]
When viewing on a small desktop or mobile screen (tested on 5" phone and 7.5" tablet in portrait and by resizing a chrome window on a desktop) each block takes up the whole screen width of the browser (height is scaled appropriately) regardless of layout on a larger screen (desktop browser or 7.5" in landscape).

This can make it quite difficult to navigate. Personally I think ti would be better if little to no scaling was applied and the mobile user is simply able to zoom in or out as appropriate. Currently, if one has many buttons it makes it difficult to quickly find the correct one or to see the general state at a glance.

I've attached a couple of example screenshots, one of the view in full screen, the remaining three show the same dashboard in a smaller window:

Full screen
![full screen](https://cloud.githubusercontent.com/assets/10153895/11609068/eaac1562-9b73-11e5-8588-f9ed8bad09eb.png)

Small screen (top)
![small screen top](https://cloud.githubusercontent.com/assets/10153895/11609070/f289ee6c-9b73-11e5-857d-2c8fefc48167.png)

Small screen (middle)
![small screen middle](https://cloud.githubusercontent.com/assets/10153895/11609074/f6d16dd8-9b73-11e5-9a1d-2a6bf4e800fb.png)

Small screen (bottom)
![small screen bottom](https://cloud.githubusercontent.com/assets/10153895/11609076/f9ce6a72-9b73-11e5-8798-365e61e07960.png)

**Comment by jwcooper** [comment]
This should be resolved. If it is not, please post in our forums the details of your issue.

https://forums.adafruit.com/viewforum.php?f=56
