### ISSUE TITLE
Feature request: trigger if no new data is published within a certain time

### ISSUE THREAD

**Issue by PhilipAnderson** [adafruit/io-issues#86]
We would like to use adafruit io to monitor the temperature of freezers and receive an alert if the temperature increases above a threshold, which is possible. However it is also desirable to be notified if the freezers stop publishing data, which could happen for a variety of reasons; Wi-Fi disconnecting etc. Is this a feature that might be added to adafruit.io in the future?

**Comment by jwcooper** [comment]
This is a feature you can enable now. It's configured directly on the feed. You can be notified if the feed is marked offline. You can also configure the time frame that is considered 'offline'.

Visit one of your feed pages, such as: https://io.adafruit.com/{username}/feeds/temperature, and click the upper EDIT button above the chart. In that modal there is a link to be notified if a feed is marked offline.
