### ISSUE TITLE
'Create feed' button in create feed menu doesn't close window

### ISSUE THREAD

**Issue by sitruss** [adafruit/io-issues#87]
Using Chrome Version 47.0.2526.80 m on Windows 10, clicking the 'create feed' button in the 'create feed' popup creates the feed but never closes the window, so I ended up making 15 identical feeds by accident from all the needless clicking.

**Comment by andrealmeidadomingues** [comment]
I have the same issue

**Comment by alex-march** [comment]
Same problem. Win Firefox 43.0.4.

**Comment by jwcooper** [comment]
This should be resolved. If it is not, please post in our forums the details of your issue.

https://forums.adafruit.com/viewforum.php?f=56
