### ISSUE TITLE
Configurable background color for dashboards 

### ISSUE THREAD

**Issue by 0xFACE** [adafruit/io-issues#88]
I would like to change the background color for my dashboards. 
Especially in fullscreen mode I like to have black background ;-)

**Comment by toddtreece** [comment]
@tylerdcooper what do you think?

**Comment by toddtreece** [comment]
we've talked it over, and we will add a lights out feature soon

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
