### ISSUE TITLE
No been able to publish into adafruit IO using ESP8266

### ISSUE THREAD

**Issue by andrealmeidadomingues** [adafruit/io-issues#90]
Hello,

Using ESP8266 ESP07

I can't seem do be able to publish on my feed's. I am able to receive data from the feed's. It say's it was successfully publish, but nothing appears on the IO page:

Sending photocell val 300...OK!

Sending photocell val 301...OK!

Sending photocell val 302...OK!

Sending photocell val 303...OK!

Any ideias of what is going on?

At the IO page the following error is displayed:

2015-12-22 19:34:43 - ERROR - feed photocell: undefined method `feeds' for nil:NilClass

**Comment by andrealmeidadomingues** [comment]
I deleted my IO account and created another one. It works now. Finally. Thanks for everyone help.

**Comment by maurbeck** [comment]
Would you like to close this issue then?

**Comment by andrealmeidadomingues** [comment]
Sure.
