### ISSUE TITLE
Can't Send GPS coordinates 

### ISSUE THREAD

**Issue by ATMEGA17** [adafruit/io-issues#92]
After making a lot of tests i can't send longitude and latitude to a feed named GPS, i'm not using a arduino based MQQT library but i'm using android app 
## i tried https://io.adafruit.com/api/docs/#!/Data/create with:

{
 "value":"55",
"lon":15,
"lat":17
## }

i don't have problem with value but with lon and lat it always be null !!
"value": "55",
  "position": null,
  "lat": null,
  "lon": null,
  "ele": null,

Help please !!

**Comment by toddtreece** [comment]
@ATMEGA17 sorry for the delay in getting back to you on this. we will look into this as soon as possible, but in the meantime you should be able to push GPS data via MQTT.

**Comment by andlier** [comment]
How exactly does one push gps data with mqtt.  Can't get it to work by just pushing a comma separated string like in the FONA examples: "34.2342,23.2344" to a feed.

**Comment by krlbaker** [comment]
Does anyone know if this got fixed? I was trying to send GPS coordinates via the API and only get "null" response.

**Comment by krlbaker** [comment]
Anyone have an update on this issue? I am still unable to send GPS coordinates in the REST API.

**Comment by anilkunchalaece** [comment]
May be you are sending them as Numbers ?
Try to insert them as String..

```
{
"value":"55",
"lon":"15",
"lat":"17"

}
```

**Comment by krlbaker** [comment]
@anilkunchalaece I have the payload in a string format. I was able to use the same payload in a MQTT publish statement and it worked. I think there is an issue with the API accepting parameters other than "value".

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
