### ISSUE TITLE
Create 2D charts with 2 or more Y-axes

### ISSUE THREAD

**Issue by ynlng** [adafruit/io-issues#94]
Hello, 

It would be nice if 2D plot chars could hold 2 or more Y axes. Example usage is the typical plot showing bothTemperature and %Humidity, at the same time. See attached screenshot. 

![screen shot 2016-01-04 at 1 15 58 pm](https://cloud.githubusercontent.com/assets/568974/12088585/60b636ec-b2e5-11e5-871e-e55c1ac653ae.png)

**Comment by toddtreece** [comment]
charts currently support up to 5 feeds, and you can select multiple feeds when creating or editing a block.

<img width="636" alt="screen shot 2016-01-04 at 10 24 19 am" src="https://cloud.githubusercontent.com/assets/360020/12092888/d989180e-b2cd-11e5-8d1f-c466d2f17157.png">

<img width="1281" alt="screen shot 2016-01-04 at 10 24 33 am" src="https://cloud.githubusercontent.com/assets/360020/12092894/dfd5130c-b2cd-11e5-9c29-89ca943e4d92.png">

**Comment by ynlng** [comment]
Yes. However, I am looking for a pair of feeds with a different axis for
each. As an example I attached a temperature/humidity graph.

**Comment by toddtreece** [comment]
@ynlng we supported that previously, but we couldn't come up with a good solution once we started allowing users to add up to five feeds to a chart. please let us know if you have ideas for how to display more than two.

**Comment by ductsoup** [comment]
Has this changed since AIO migrated to the new chart library or is it still on the list of things to revisit?

**Comment by toddtreece** [comment]
@ductsoup we migrated to http://metricsgraphicsjs.org/, and we are currently transitioning all of the frontend javascript to react.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
