### ISSUE TITLE
All feeds were renamed on Dec 31st 2015!

### ISSUE THREAD

**Issue by z-l-p** [adafruit/io-issues#95]
My dashboard broke a few days ago. It turns out that all my feeds were magically duplicated on December 31st without my intervention. The new feeds are all lower-case (were mixed case), have a "1" appended to their keys, and new ID numbers in the 50k range. 

So **pondstation-transmitState** became **pondstation-transmitstate** .

That's OK with me, since the API doesn't appear to be case-sensitive and my data is reaching the new feeds, BUT the dashboard is case-sensitive so it broke. (I can remake it, but I thought the devs would be interested in this error.)

Also see this forum thread:
https://forums.adafruit.com/viewtopic.php?f=56&t=86833

**Comment by jwcooper** [comment]
If this is still an issue, can you post the updated details to our forum? We're consolidating our issues and enhancement requests.

https://forums.adafruit.com/viewforum.php?f=56
