### ISSUE TITLE
Dashboards not going public

### ISSUE THREAD

**Issue by jwcooper** [adafruit/io-issues#96]
From forums:
I have 4 dashboards, I am trying to change two of them to be public, but it seems that whatever I change only the default one is changed, and also the icon stay the same so no indication.

**Comment by roadfun** [comment]
I am having this issue as well. I haven't seen an update on the forum thread. Is this being addressed? Anything we can do to help?

**Comment by DarkCompiled** [comment]
Me too, I have 3 dashboards but only 2 are currently public.
Every time I try to make the third one public, the first one gets private!

**Comment by chrowe** [comment]
For me, the lock icon just doesn't do anything.
My one public dashboard won't change to private and my 2 private dashboards won't go public
e.g. https://io.adafruit.com/chrowe/root-cellar

I am on a Mac 10.11.3 (15D21) and tested on Chrome and Firefox (both recently updated within the last few weeks.

When I made the one dashboard public before, it had issues and I had to try several times before it stuck.

**Comment by chrowe** [comment]
This is the warning I am getting in the console.
```
Mixed Content: The page at 'https://io.adafruit.com/chrowe/root-cellar#?editing=true' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://io.adafruit.com/'. This content should also be served over HTTPS.
```

**Comment by chrowe** [comment]
Has anyone found a fix or a workaround for this?

**Comment by toddtreece** [comment]
we'll be pushing a fix for this today. sorry for the delay

**Comment by chrowe** [comment]
Awesome! io is the best tool I have found out there and I am excited to be able to share my data with others again :)

**Comment by roadfun** [comment]
My thanks as well. I think people will find my dashboard data helpful. 
Ron

**Comment by mikehole** [comment]
Hi,

It's 19 hours since your post and still having this issue just checking has the fix been applied yet. Apologies for looking impatient. 

Cheers,

Mike

**Comment by jwcooper** [comment]
We've deployed a fix for this issue. Please let us know if you run into any other issues.

Thanks!

**Comment by chrowe** [comment]
Works like a charm

**Comment by roadfun** [comment]
Working for me as well. Thanks for the fix.

**Comment by mikehole** [comment]
Great stuff guys. Was able to show off some stuff in time yesterday before the weekend. Looking forward to seeing how the platform matures 😊

**Comment by arttuladhar** [comment]
😞 Broken Again
