### ISSUE TITLE
Enhancement: Graph and Gauge limits with color coding

### ISSUE THREAD

**Issue by agrzywi** [adafruit/io-issues#97]
The graph and gauge widgets would both benefit from having an option for upper and lower control limits, and for the gauges, values outside of those limits could be set with a color-picker. 

A simple way to think about this is with the dashboard I've built for monitoring temperatures: I'm plotting the temperatures over time and it would sure be great to establish (and see) an upper and lower limit. It would allow me to get up in the morning and quickly see that overnight one of my sensors, e.g., exceeded the upper threshold. On a gauge, which is showing moment-in-time, the widget could go the extra step of changing the color of some feature of the gauges--letting you know with a quick glance of your dashboard that one of your sensors is outside of threshold. 

While this would work nicely for temperatures, it works equally well for other things that you might want to plot or gauge: Ping time, distance, light-levels, etc. If you're plotting it or gauging it, you'd love to know whether its in bounds or out of bounds. 

[graphs and gauges.pdf](https://github.com/adafruit/io-issues/files/78972/graphs.and.gauges.pdf)

Let me know if I can do anything more to help!

**Comment by ATMEGA17** [comment]
Is this a suggestion or you already did this ? if yes let us know how, it's a great work friend

**Comment by agrzywi** [comment]
A suggestion only, I’m afraid. I don’t think I have the development chops to code it. I just mocked up the images in Powerpoint. :-) 

(What language are you folks working in?) 

If you pursue it, is there anything else I could do to help? I wrote up everything I could think of, but maybe there are some holes. Would it help if I wrote up some test cases, or anything like that? 

Cheers!

AG

**Comment by toddtreece** [comment]
@agrzywi thanks for the suggestion, and detailed mockup. @tylerdcooper what do you think?

**Comment by tylerdcooper** [comment]
@agrzywi Thanks for the mockup. We do plan to add advanced features to many of the blocks we have in the future. We will definitely keep your suggestions in mind when we update the graph and gauges.

**Comment by chrowe** [comment]
I am seeing a min/max and the color changes when outside those ranges.
No color picker yet though.

**Comment by chrowe** [comment]
Is it possible that the colors would change on a graph after it was created? On https://io.adafruit.com/chrowe/garn-dashboard I used the block title field to create a graph legend but it looks like the colors have switched at some point.

![screen shot 2016-10-27 at 1 54 24 pm](https://cloud.githubusercontent.com/assets/240115/19778962/0b5a332c-9c4d-11e6-8523-833115c037c5.png)

I am going to fix this now but want to make sure it won't happen again.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
