### ISSUE TITLE
Graph: history over 12 hours is truncated

### ISSUE THREAD

**Issue by jaromir-sukuba** [adafruit/io-issues#98]
I'm sending data from ESP8266 hardware, approximately every 50 seconds to two feeds and displaying them into graph, see https://io.adafruit.com/jaromir/test2#
When HOURS OF HISTORY is set to value over 12, it shows only last 12 hours, no matter what number is here, though there are data older than 12 hours in the feeds. 
If it is feature, user should be warned after entering higher than acceptable number.

**Comment by toddtreece** [comment]
@jaromir-sukuba sorry for the delay in getting back to you. it looks like i can reproduce this issue, and we will work on a fix

**Comment by ribico** [comment]
Perhaps it is the same of #31 ??

**Comment by beinnlora** [comment]
+1 for issues of dashboard graphs only plotting last 1000 points. yet 
jwcooper commented on Aug 25, 2015 in [#31](https://github.com/adafruit/io-issues/issues/31) that this is a computer/browser limitation, 
however, when you view the raw feed this happily renders/shows the entire history of the feed (>12,000 points), so this is feasible even on old computer like mine.
**Example feed** that updates once per minute:
raw feed showing all data points > 12000: works fine:
[](https://io.adafruit.com/steve098/feeds/aisbatteryl)
But when shown on a dashboard, feed that is set to 120hr history (~7200 out of 12000 data points in set) then only the previous ~16.6 hrs is displayed (c.f. 1000 datapoints)
[](https://io.adafruit.com/steve098/aismon)

**Comment by jwcooper** [comment]
@beinnlora The feeds page is also only showing ~1000 records. It chooses every nth record, with n being the value of the total records over 1000. Also, dashboards are a bit different as you could have 10 separate charts on each dashboard. Have to be a bit more careful there.

That being said, we do plan on increasing and optimizing this over time.

**Comment by jwcooper** [comment]
Thanks for the feedback. We're tracking this internally now as well. Further issues or enhancement requests can go to our forum as we're consolidating our support and issues: https://forums.adafruit.com/viewforum.php?f=56
